"""
Chapter 5 Exercises: Software Design & Best Practices

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

from typing import List, Dict, Any
from abc import ABC, abstractmethod


# =============================================================================
# Exercise 1: Refactor Spaghetti ML Code Into Clean Functions
# =============================================================================
# The function below is a monolithic mess. Refactor it into small, well-named
# functions: load_data, compute_gradient, train_step, and evaluate_mse.
#
# Requirements:
#   - Each function should have a single responsibility
#   - Use descriptive names (PEP 8)
#   - Extract magic numbers as constants or parameters

def refactored_training_pipeline(data: List[List[float]], epochs: int = 500, lr: float = 0.05):
    """
    Refactored version: takes data (rows of [x1, x2, ..., y]), trains y = w*x + b
    (single feature), returns (w, b, final_mse).
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 2: Implement the Strategy Pattern for Model Selection
# =============================================================================
# Create an abstract ModelStrategy with a predict() method. Implement two
# strategies: LinearStrategy (y = w*x + b) and NullStrategy (predict 0).
# Create a Predictor class that takes a strategy and delegates predict() to it.

class ModelStrategy(ABC):
    """Abstract strategy for model prediction."""

    @abstractmethod
    def predict(self, X: List[float]) -> List[float]:
        pass


class LinearStrategy(ModelStrategy):
    def __init__(self, w: float = 1.0, b: float = 0.0):
        # YOUR CODE HERE
        pass

    def predict(self, X: List[float]) -> List[float]:
        # YOUR CODE HERE
        pass


class NullStrategy(ModelStrategy):
    def predict(self, X: List[float]) -> List[float]:
        # YOUR CODE HERE
        pass


class Predictor:
    """Uses a ModelStrategy to make predictions."""

    def __init__(self, strategy: ModelStrategy):
        # YOUR CODE HERE
        pass

    def predict(self, X: List[float]) -> List[float]:
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 3: Write Unit Tests for a Data Preprocessing Pipeline
# =============================================================================
# Implement a function normalize_and_clip(data, mean, std, low, high) that
# normalizes then clips. Then write 3 test functions: test_normalize_basic,
# test_clip_extreme_values, test_empty_input. Use assertions (pytest or unittest).

def normalize_and_clip(
    data: List[float],
    mean: float,
    std: float,
    low: float = -3.0,
    high: float = 3.0,
) -> List[float]:
    """Z-score normalize then clip to [low, high]."""
    # YOUR CODE HERE
    pass


def test_normalize_basic():
    """Test that normalize produces mean≈0, std≈1 for normal data."""
    # YOUR CODE HERE
    pass


def test_clip_extreme_values():
    """Test that values outside [low, high] are clipped."""
    # YOUR CODE HERE
    pass


def test_empty_input():
    """Test that empty list returns empty list."""
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 4: Create a Configuration System for an ML Experiment
# =============================================================================
# Implement a Config class that:
#   - Accepts a dict (e.g., from JSON/YAML)
#   - Has attributes: learning_rate, epochs, model_name
#   - Has a validate() method that raises ValueError for invalid values
#   - Has a from_dict(cls, d) class method

class Config:
    def __init__(self, learning_rate: float, epochs: int, model_name: str):
        # YOUR CODE HERE
        pass

    def validate(self) -> None:
        """Raise ValueError if any field is invalid."""
        # YOUR CODE HERE
        pass

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Config":
        """Create Config from dict. Keys: learning_rate, epochs, model_name."""
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 5: Build a Complete Mini ML Project With Proper Structure
# =============================================================================
# Create a minimal pipeline with:
#   - DataLoader: from_rows(data, target_idx) -> (X, y)
#   - SimpleModel: fit(X, y), predict(X)
#   - Trainer: fit(model, data_loader, config)
#   - run_experiment(config, data) -> trained model
#
# Data format: list of rows, last column is target. Model: single linear layer.

class DataLoader:
    def __init__(self, data: List[List[float]], target_idx: int = -1):
        # YOUR CODE HERE
        pass

    def get_xy(self):
        # YOUR CODE HERE
        pass


class SimpleModel:
    def __init__(self):
        # YOUR CODE HERE
        pass

    def fit(self, X: List[List[float]], y: List[float], epochs: int = 100, lr: float = 0.01):
        # YOUR CODE HERE
        pass

    def predict(self, X: List[List[float]]) -> List[float]:
        # YOUR CODE HERE
        pass


class Trainer:
    def __init__(self, config: Dict[str, Any]):
        # YOUR CODE HERE
        pass

    def fit(self, model: SimpleModel, data_loader: DataLoader) -> None:
        # YOUR CODE HERE
        pass


def run_experiment(config: Dict[str, Any], data: List[List[float]]) -> SimpleModel:
    """Run full pipeline and return trained model."""
    # YOUR CODE HERE
    pass


if __name__ == "__main__":
    print("Chapter 5 Exercises")
    print("=" * 40)
    print("Implement the functions/classes above,")
    print("then check solutions/solutions.py!")
