"""
Exercises — Chapter 9: Deep Learning Fundamentals
Generated by Berta AI | Created by Luigi Pascal Rondanini

Five exercises covering perceptrons, backpropagation, PyTorch classifiers,
dropout, and CNNs.  Fill in every `YOUR CODE HERE` block.
"""

import numpy as np

# ===================================================================
# Exercise 1 — Implement a Perceptron
# ===================================================================

class Perceptron:
    """
    A single-layer Perceptron for binary classification.

    Attributes
    ----------
    lr : float
        Learning rate.
    n_epochs : int
        Number of training epochs.
    weights : np.ndarray or None
        Weight vector (set after fitting).
    bias : float
        Bias term.

    Methods
    -------
    fit(X, y)
        Train the perceptron on input matrix X and binary labels y ∈ {0, 1}.
    predict(X)
        Return binary predictions using the step activation.
    """

    def __init__(self, lr=0.01, n_epochs=1000):
        self.lr = lr
        self.n_epochs = n_epochs
        self.weights = None
        self.bias = 0.0

    def _step(self, z):
        """Binary step activation: returns 1 if z >= 0, else 0."""
        # YOUR CODE HERE
        pass

    def fit(self, X, y):
        """
        Train on X (n_samples, n_features) and binary labels y (n_samples,).
        Initialise weights to zeros. For each epoch, iterate over every sample,
        compute prediction, and update weights/bias with the perceptron rule.
        """
        # YOUR CODE HERE
        pass

    def predict(self, X):
        """Return binary predictions for X (n_samples, n_features)."""
        # YOUR CODE HERE
        pass


# ===================================================================
# Exercise 2 — Implement Backpropagation for a 2-Layer Network
# ===================================================================

class NeuralNet2Layer:
    """
    A 2-layer (one hidden layer) neural network trained via backpropagation.

    Architecture: input → hidden (sigmoid) → output (sigmoid)
    Loss: Binary cross-entropy.

    Parameters
    ----------
    n_input : int
    n_hidden : int
    n_output : int
    lr : float
    seed : int
    """

    def __init__(self, n_input, n_hidden, n_output=1, lr=0.1, seed=42):
        self.lr = lr
        rng = np.random.RandomState(seed)
        self.W1 = rng.randn(n_input, n_hidden) * 0.5
        self.b1 = np.zeros((1, n_hidden))
        self.W2 = rng.randn(n_hidden, n_output) * 0.5
        self.b2 = np.zeros((1, n_output))

    @staticmethod
    def _sigmoid(z):
        return 1.0 / (1.0 + np.exp(-np.clip(z, -500, 500)))

    def forward(self, X):
        """
        Compute forward pass.  Store intermediate values as self.Z1, self.A1,
        self.Z2, self.A2 so backward() can use them.
        Return the output activations (self.A2).
        """
        # YOUR CODE HERE
        pass

    def backward(self, X, y):
        """
        Compute gradients via backpropagation and update all weights/biases.
        y shape: (m, 1).
        """
        # YOUR CODE HERE
        pass

    def train(self, X, y, epochs=2000, verbose=True):
        """
        Training loop. Return list of epoch losses.
        Print loss every epochs//10 steps if verbose is True.
        """
        # YOUR CODE HERE
        pass


# ===================================================================
# Exercise 3 — Build a PyTorch Classifier
# ===================================================================

def build_and_train_classifier(X, y, n_hidden=16, epochs=500, lr=0.01):
    """
    Build and train a binary classifier using PyTorch.

    Requirements:
    - Use torch.nn.Module subclass with at least one hidden layer + ReLU.
    - Loss: BCEWithLogitsLoss
    - Optimiser: Adam
    - Return (trained_model, loss_history).

    Parameters
    ----------
    X : np.ndarray (n_samples, n_features)
    y : np.ndarray (n_samples,)
    n_hidden : int
    epochs : int
    lr : float

    Returns
    -------
    model : nn.Module
    loss_history : list[float]
    """
    # YOUR CODE HERE
    pass


# ===================================================================
# Exercise 4 — Implement Dropout from Scratch
# ===================================================================

def apply_dropout(A, keep_prob=0.8, seed=None):
    """
    Apply inverted dropout to activation matrix A.

    Steps:
    1. Generate a random mask with the same shape as A where each element
       is 1 with probability keep_prob, else 0.
    2. Element-wise multiply A by the mask.
    3. Scale the result by (1 / keep_prob) to maintain expected values.

    Parameters
    ----------
    A : np.ndarray
        Activation matrix, any shape.
    keep_prob : float
        Probability of keeping each unit (0 < keep_prob <= 1).
    seed : int or None
        Optional random seed.

    Returns
    -------
    A_dropped : np.ndarray
        Activations after dropout + scaling.
    mask : np.ndarray
        The binary mask that was applied.
    """
    # YOUR CODE HERE
    pass


# ===================================================================
# Exercise 5 — End-to-End CNN Pipeline
# ===================================================================

def build_cnn_pipeline(n_samples=500, n_epochs=5, seed=42):
    """
    Create synthetic image data, build a small CNN in PyTorch, train it,
    and return the model and final accuracy.

    Requirements:
    - Synthetic data: random 1-channel 8×8 images, 2 classes.
    - CNN: at least one Conv2d + ReLU + Flatten + Linear layer.
    - Loss: CrossEntropyLoss.
    - Optimiser: Adam.
    - Return (model, accuracy) where accuracy is on the training set.

    Parameters
    ----------
    n_samples : int
    n_epochs : int
    seed : int

    Returns
    -------
    model : nn.Module
    accuracy : float
    """
    # YOUR CODE HERE
    pass
