"""
Chapter 6 Exercises: Introduction to Machine Learning

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np


# =============================================================================
# Exercise 1: Implement Train/Test Split From Scratch
# =============================================================================
# Split X and y into train and test sets. Use test_ratio (e.g., 0.2) for the
# proportion of data in the test set. Shuffle indices with random_state for
# reproducibility.
#
# Example:
#   X, y = [1,2,3,4,5], [1,2,3,4,5]
#   X_train, X_test, y_train, y_test = train_test_split_scratch(X, y, 0.2, 42)

def train_test_split_scratch(X, y, test_ratio=0.2, random_state=None):
    """Return (X_train, X_test, y_train, y_test)."""
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 2: Calculate Precision, Recall, F1 From a Confusion Matrix
# =============================================================================
# Given TP, FP, FN, TN (counts from a 2x2 confusion matrix), compute and
# return a dict with keys: 'precision', 'recall', 'f1'.
#
# Precision = TP / (TP + FP)
# Recall = TP / (TP + FN)
# F1 = 2 * (Precision * Recall) / (Precision + Recall)
#
# Handle division by zero (return 0.0).

def confusion_metrics(tp, fp, fn, tn):
    """Return {'precision': ..., 'recall': ..., 'f1': ...}."""
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 3: Implement K-Fold Cross-Validation From Scratch
# =============================================================================
# Given X, y, model (sklearn estimator with .fit and .predict), k (number of
# folds), and a scoring function score_fn(y_true, y_pred) that returns a
# scalar (higher is better, e.g., negative MSE), return the mean and std
# of the k fold scores.
#
# Split indices into k folds. For each fold, train on k-1 parts, predict on
# the held-out part, compute score. Return (mean_scores, std_scores).

def k_fold_cv(X, y, model, k=5, score_fn=None, random_state=42):
    """
    Return (mean_score, std_score).
    score_fn(y_true, y_pred) -> scalar. Default: negative MSE for regression.
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 4: Build a Complete Pipeline
# =============================================================================
# Load data from filepath (CSV), use target_col and feature_cols.
# 1. Load with pandas
# 2. Split into train/test (80/20)
# 3. Scale features with StandardScaler
# 4. Train a LogisticRegression
# 5. Evaluate with accuracy, precision, recall, F1
# Return dict: {'accuracy': ..., 'precision': ..., 'recall': ..., 'f1': ...}
#
# Assume target is binary (0/1 or 'Yes'/'No'). Handle encoding if needed.

def build_pipeline(filepath, target_col, feature_cols, random_state=42):
    """Return evaluation metrics dict."""
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 5: Compare 3 Models on a Dataset
# =============================================================================
# Given filepath, target_col, feature_cols, and a list of (name, model) tuples,
# load data, split 80/20, scale, train each model, and return a list of dicts:
# [{'model': name, 'accuracy': ..., 'f1': ...}, ...]
# Sort by F1 descending.

def compare_models_on_dataset(filepath, target_col, feature_cols, models):
    """
    models: list of (name, model) e.g. [('LR', LogisticRegression()), ...]
    Return list of dicts sorted by F1 desc.
    """
    # YOUR CODE HERE
    pass


if __name__ == "__main__":
    print("Chapter 6 Exercises")
    print("=" * 40)
    print("Implement the functions above,")
    print("then check solutions/solutions.py!")
