"""
Chapter 3 Exercises: Linear Algebra & Calculus

Generated by Berta AI | Created by Luigi Giacobbe
"""

import math


# =============================================================================
# Exercise 1: Implement Cosine Similarity Between Vectors
# =============================================================================
# Cosine similarity = (u·v) / (||u|| * ||v||). Range: -1 to 1.
# Used extensively in NLP for comparing word embeddings.
#
# Example:
#   cosine_similarity([1, 0], [1, 0]) -> 1.0  (identical direction)
#   cosine_similarity([1, 0], [-1, 0]) -> -1.0 (opposite direction)

def cosine_similarity(u, v):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 2: Matrix-Vector Multiplication From Scratch
# =============================================================================
# Implement matrix-vector multiply: (m×n) matrix @ (n) vector -> (m) vector.
# This is the core computation in every linear layer of a neural network.
#
# Example:
#   A = [[1, 2], [3, 4]], x = [5, 6]
#   matrix_vector_multiply(A, x) -> [17, 39]  (1*5+2*6=17, 3*5+4*6=39)

def matrix_vector_multiply(A, x):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 3: Compute Gradient of a Simple Function
# =============================================================================
# For f(x, y) = x² + 2xy + y², compute the gradient analytically.
# Return [∂f/∂x, ∂f/∂y] as a list.
#
# Hint: ∂f/∂x = 2x + 2y, ∂f/∂y = 2x + 2y

def gradient_f(x, y):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 4: Implement Gradient Descent for a Quadratic Function
# =============================================================================
# Minimize f(x, y) = x² + y² using gradient descent.
# Start at (x0, y0), run for `epochs` iterations with given learning rate.
# Return the final (x, y) and the final loss value.
#
# Hint: ∇f = (2x, 2y). Update: x -= lr * 2x, y -= lr * 2y

def gradient_descent_quadratic(x0, y0, learning_rate=0.1, epochs=100):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 5: Build a Simple Linear Regression Class
# =============================================================================
# Implement a LinearRegression class with:
#   - fit(X, y): train using gradient descent (MSE loss)
#   - predict(X): return predictions
#
# Assume single feature for simplicity: y = w*x + b
# X and y are lists of numbers.

class LinearRegression:
    def __init__(self, learning_rate=0.01, epochs=1000):
        # YOUR CODE HERE
        pass

    def fit(self, X, y):
        # YOUR CODE HERE
        pass

    def predict(self, X):
        # YOUR CODE HERE
        pass


if __name__ == "__main__":
    print("Chapter 3 Exercises")
    print("=" * 40)
    print("Implement the functions/classes above,")
    print("then check solutions/solutions.py!")
