"""
Chapter 2 Exercises: Data Structures & Algorithms

Generated by Berta AI | Created by Luigi Giacobbe
"""


# =============================================================================
# Exercise 1: Implement a Queue using Two Stacks
# =============================================================================
# Implement enqueue and dequeue using only two lists acting as stacks (append/pop).
# This is a classic interview question that tests understanding of both structures.

class QueueFromStacks:
    def __init__(self):
        # YOUR CODE HERE
        pass

    def enqueue(self, item):
        # YOUR CODE HERE
        pass

    def dequeue(self):
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 2: Find K Closest Points
# =============================================================================
# Given a list of (x, y) points and a target point, find the k closest points.
# Use a heap for O(n log k) efficiency.
#
# Example:
#   points = [(1,1), (3,3), (2,2), (5,5), (0,0)]
#   k_closest(points, target=(2,2), k=3)
#   -> [(2,2), (1,1), (3,3)]

def k_closest(points, target, k):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 3: Longest Common Subsequence
# =============================================================================
# Find the length of the longest common subsequence between two strings.
# Use dynamic programming.
#
# Example:
#   lcs("machine", "aching") -> 6  ("achin" + "g" -> "aching")

def lcs(s1, s2):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 4: Cycle Detection in Directed Graph
# =============================================================================
# Given an adjacency list, detect if the graph has a cycle.
# Important for: validating ML pipeline DAGs.
#
# Example:
#   has_cycle({"a": ["b"], "b": ["c"], "c": ["a"]}) -> True
#   has_cycle({"a": ["b"], "b": ["c"], "c": []}) -> False

def has_cycle(graph):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 5: Implement an LRU Cache
# =============================================================================
# Least Recently Used cache with O(1) get and put.
# Used in: model caching, API response caching, embedding caching.
#
# LRUCache(capacity=3)
# cache.put("a", 1), cache.put("b", 2), cache.put("c", 3)
# cache.get("a") -> 1 (marks "a" as recently used)
# cache.put("d", 4)  -> evicts "b" (least recently used)

class LRUCache:
    def __init__(self, capacity):
        # YOUR CODE HERE
        pass

    def get(self, key):
        # YOUR CODE HERE
        pass

    def put(self, key, value):
        # YOUR CODE HERE
        pass


if __name__ == "__main__":
    print("Chapter 2 Exercises")
    print("=" * 40)
    print("Implement the functions/classes above,")
    print("then check solutions/solutions.py!")
