"""
Unsupervised Learning Toolkit - Core implementations and plotting utilities.
Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_samples, silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.datasets import make_blobs


class KMeansScratch:
    """
    K-Means clustering implementation from scratch.
    """

    def __init__(self, n_clusters=3, max_iters=100, random_state=42):
        """
        Initialize K-Means.

        Parameters
        ----------
        n_clusters : int
            Number of clusters.
        max_iters : int
            Maximum iterations for the algorithm.
        random_state : int
            Random seed for reproducibility.
        """
        self.n_clusters = n_clusters
        self.max_iters = max_iters
        self.random_state = random_state
        self.centroids = None
        self.labels_ = None
        self.inertia_history = []

    def fit(self, X):
        """
        Fit K-Means to the data.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training data.

        Returns
        -------
        self
        """
        X = np.asarray(X)
        np.random.seed(self.random_state)
        n_samples = X.shape[0]

        # Random centroid initialization
        idx = np.random.choice(n_samples, self.n_clusters, replace=False)
        self.centroids = X[idx].copy()

        for _ in range(self.max_iters):
            # Assign points to nearest centroid
            labels = self._assign_clusters(X)
            # Recompute centroids
            new_centroids = np.zeros_like(self.centroids)
            for k in range(self.n_clusters):
                mask = labels == k
                if np.any(mask):
                    new_centroids[k] = X[mask].mean(axis=0)
                else:
                    new_centroids[k] = self.centroids[k]

            inertia = self._compute_inertia(X, labels, new_centroids)
            self.inertia_history.append(inertia)

            if np.allclose(self.centroids, new_centroids):
                break
            self.centroids = new_centroids

        self.labels_ = self._assign_clusters(X)
        return self

    def _assign_clusters(self, X):
        """Assign each point to the nearest centroid."""
        distances = np.linalg.norm(X[:, np.newaxis] - self.centroids, axis=2)
        return np.argmin(distances, axis=1)

    def predict(self, X):
        """
        Predict cluster labels for new data.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Data to predict.

        Returns
        -------
        labels : ndarray of shape (n_samples,)
            Cluster indices.
        """
        X = np.asarray(X)
        return self._assign_clusters(X)

    def fit_predict(self, X):
        """
        Fit and return cluster labels.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training data.

        Returns
        -------
        labels : ndarray of shape (n_samples,)
            Cluster indices.
        """
        return self.fit(X).labels_

    def _compute_inertia(self, X, labels, centroids):
        """
        Compute within-cluster sum of squares (inertia).

        Parameters
        ----------
        X : ndarray
            Data points.
        labels : ndarray
            Cluster labels.
        centroids : ndarray
            Cluster centroids.

        Returns
        -------
        inertia : float
        """
        inertia = 0.0
        for k in range(self.n_clusters):
            mask = labels == k
            if np.any(mask):
                inertia += np.sum((X[mask] - centroids[k]) ** 2)
        return inertia


class PCAScratch:
    """
    Principal Component Analysis implementation from scratch.
    """

    def __init__(self, n_components=2):
        """
        Initialize PCA.

        Parameters
        ----------
        n_components : int
            Number of components to keep.
        """
        self.n_components = n_components
        self.mean_ = None
        self.components_ = None
        self.explained_variance_ = None

    def fit(self, X):
        """
        Fit PCA to the data.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training data.

        Returns
        -------
        self
        """
        X = np.asarray(X)
        self.mean_ = X.mean(axis=0)
        X_centered = X - self.mean_

        # Covariance matrix
        cov = np.cov(X_centered.T)

        # Eigendecomposition
        eigenvalues, eigenvectors = np.linalg.eigh(cov)
        idx = np.argsort(eigenvalues)[::-1]
        eigenvalues = eigenvalues[idx]
        eigenvectors = eigenvectors[:, idx]

        n = min(self.n_components, len(eigenvalues))
        self.components_ = eigenvectors[:, :n].T
        self.explained_variance_ = eigenvalues[:n]
        return self

    def transform(self, X):
        """
        Project data onto principal components.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Data to transform.

        Returns
        -------
        X_transformed : ndarray of shape (n_samples, n_components)
        """
        X = np.asarray(X)
        X_centered = X - self.mean_
        return X_centered @ self.components_.T

    def fit_transform(self, X):
        """
        Fit and transform in one step.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training data.

        Returns
        -------
        X_transformed : ndarray of shape (n_samples, n_components)
        """
        return self.fit(X).transform(X)

    @property
    def explained_variance_ratio_(self):
        """Fraction of variance explained by each component."""
        total = np.sum(self.explained_variance_)
        return self.explained_variance_ / total if total > 0 else self.explained_variance_


def plot_clusters(X, labels, centroids=None, title="Clusters"):
    """
    Scatter plot of clustered data with optional centroid markers.

    Parameters
    ----------
    X : array-like
        Data points (2D).
    labels : array-like
        Cluster labels.
    centroids : array-like, optional
        Centroids to plot as markers.
    title : str
        Plot title.
    """
    X = np.asarray(X)
    labels = np.asarray(labels)
    plt.figure(figsize=(8, 6))
    scatter = plt.scatter(X[:, 0], X[:, 1], c=labels, cmap="viridis", alpha=0.7, edgecolors="k")
    if centroids is not None:
        centroids = np.asarray(centroids)
        plt.scatter(centroids[:, 0], centroids[:, 1], c="red", marker="X", s=200, edgecolors="black")
    plt.colorbar(scatter, label="Cluster")
    plt.title(title)
    plt.xlabel("Feature 1")
    plt.ylabel("Feature 2")
    plt.tight_layout()
    plt.show()


def plot_elbow(K_range, inertias, title="Elbow Method"):
    """
    Line plot of inertia vs K for elbow method.

    Parameters
    ----------
    K_range : array-like
        Range of K values.
    inertias : array-like
        Inertia for each K.
    title : str
        Plot title.
    """
    plt.figure(figsize=(8, 5))
    plt.plot(K_range, inertias, "bo-")
    plt.xlabel("Number of clusters (K)")
    plt.ylabel("Inertia")
    plt.title(title)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()


def plot_silhouette(X, labels, title="Silhouette Analysis"):
    """
    Silhouette plot using sklearn.metrics.

    Parameters
    ----------
    X : array-like
        Data points.
    labels : array-like
        Cluster labels.
    title : str
        Plot title.
    """
    X = np.asarray(X)
    labels = np.asarray(labels)
    n_clusters = len(np.unique(labels))
    silhouette_vals = silhouette_samples(X, labels)
    score = silhouette_score(X, labels)

    plt.figure(figsize=(10, 6))
    y_lower = 10
    for i in range(n_clusters):
        cluster_silhouette = silhouette_vals[labels == i]
        cluster_silhouette.sort()
        size = cluster_silhouette.shape[0]
        y_upper = y_lower + size
        plt.fill_betweenx(np.arange(y_lower, y_upper), 0, cluster_silhouette, alpha=0.7)
        plt.text(-0.05, y_lower + 0.5 * size, str(i))
        y_lower = y_upper + 10

    plt.axvline(x=score, color="red", linestyle="--", label=f"Avg: {score:.3f}")
    plt.xlabel("Silhouette coefficient")
    plt.ylabel("Cluster label")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.show()


def plot_dendrogram(X, method="ward", title="Dendrogram"):
    """
    Hierarchical clustering dendrogram using scipy.

    Parameters
    ----------
    X : array-like
        Data points.
    method : str
        Linkage method ('ward', 'complete', 'average', 'single').
    title : str
        Plot title.
    """
    X = np.asarray(X)
    linkage_matrix = linkage(X, method=method)
    plt.figure(figsize=(10, 6))
    dendrogram(linkage_matrix)
    plt.title(title)
    plt.xlabel("Sample index or (cluster size)")
    plt.ylabel("Distance")
    plt.tight_layout()
    plt.show()


def plot_pca_variance(pca, title="PCA Variance Explained"):
    """
    Bar chart and cumulative line for PCA variance explained.

    Parameters
    ----------
    pca : PCAScratch
        Fitted PCA object.
    title : str
        Plot title.
    """
    ratios = pca.explained_variance_ratio_
    cumsum = np.cumsum(ratios)
    n = len(ratios)

    fig, ax1 = plt.subplots(figsize=(8, 5))
    x = np.arange(1, n + 1)
    ax1.bar(x - 0.2, ratios, 0.4, label="Individual", color="steelblue")
    ax1.set_xlabel("Principal Component")
    ax1.set_ylabel("Variance explained ratio")
    ax1.set_xticks(x)

    ax2 = ax1.twinx()
    ax2.plot(x, cumsum, "ro-", label="Cumulative")
    ax2.set_ylabel("Cumulative variance")
    ax2.set_ylim(0, 1.05)

    plt.title(title)
    fig.legend(loc="upper right", bbox_to_anchor=(1, 1), bbox_transform=ax1.transAxes)
    plt.tight_layout()
    plt.show()


def plot_anomalies(X, labels, title="Anomaly Detection"):
    """
    Scatter plot for normal vs anomaly points.

    Parameters
    ----------
    X : array-like
        Data points (2D).
    labels : array-like
        Binary labels (0=normal, 1=anomaly or similar).
    title : str
        Plot title.
    """
    X = np.asarray(X)
    labels = np.asarray(labels)
    plt.figure(figsize=(8, 6))
    normal = labels == 0
    anomaly = labels == 1
    plt.scatter(X[normal, 0], X[normal, 1], c="steelblue", alpha=0.7, label="Normal")
    plt.scatter(X[anomaly, 0], X[anomaly, 1], c="red", alpha=0.7, label="Anomaly")
    plt.xlabel("Feature 1")
    plt.ylabel("Feature 2")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    # Demo: Generate blobs, run KMeansScratch
    X_blobs, _ = make_blobs(n_samples=300, n_features=2, centers=4, random_state=42)
    kmeans = KMeansScratch(n_clusters=4, max_iters=100, random_state=42)
    kmeans.fit(X_blobs)
    print("KMeansScratch inertia:", kmeans.inertia_history[-1] if kmeans.inertia_history else "N/A")

    # Demo: Run PCAScratch on 4D dataset
    X_4d, _ = make_blobs(n_samples=200, n_features=4, centers=3, random_state=42)
    pca = PCAScratch(n_components=4)
    pca.fit(X_4d)
    print("PCA variance explained:", pca.explained_variance_ratio_)

    print("Demo complete.")
