"""
Helper utilities for unsupervised learning.
Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


def scale_features(X):
    """
    Scale features using StandardScaler (zero mean, unit variance).

    Parameters
    ----------
    X : array-like of shape (n_samples, n_features)
        Data to scale.

    Returns
    -------
    X_scaled : ndarray of shape (n_samples, n_features)
        Scaled data.
    """
    scaler = StandardScaler()
    return scaler.fit_transform(X)


def generate_synthetic_customers(n=300, seed=42):
    """
    Generate synthetic customer data for clustering/segmentation.

    Parameters
    ----------
    n : int
        Number of customers to generate.
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    df : pandas.DataFrame
        DataFrame with columns: age, income, spending_score, visits, online_ratio.
    """
    np.random.seed(seed)
    age = np.random.randint(18, 70, size=n)
    income = np.random.exponential(scale=30000, size=n).astype(int) + 20000
    spending_score = np.random.exponential(scale=50, size=n).astype(int) + 10
    visits = np.random.poisson(lam=5, size=n) + 1
    online_ratio = np.random.beta(2, 2, size=n)
    return pd.DataFrame({
        "age": age,
        "income": income,
        "spending_score": spending_score,
        "visits": visits,
        "online_ratio": online_ratio,
    })


def generate_synthetic_sensors(n=200, anomaly_fraction=0.1, seed=42):
    """
    Generate synthetic sensor data with anomalies.

    Parameters
    ----------
    n : int
        Number of sensor readings.
    anomaly_fraction : float
        Fraction of readings that are anomalies (0 to 1).
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    df : pandas.DataFrame
        DataFrame with columns: temp, pressure, vibration, is_anomaly.
    """
    np.random.seed(seed)
    n_anomaly = int(n * anomaly_fraction)
    n_normal = n - n_anomaly

    # Normal readings
    temp_normal = np.random.normal(25, 2, n_normal)
    pressure_normal = np.random.normal(100, 5, n_normal)
    vibration_normal = np.random.exponential(0.5, n_normal)

    # Anomalous readings (outliers)
    temp_anomaly = np.random.uniform(50, 90, n_anomaly)
    pressure_anomaly = np.random.uniform(150, 200, n_anomaly)
    vibration_anomaly = np.random.exponential(5, n_anomaly)

    temp = np.concatenate([temp_normal, temp_anomaly])
    pressure = np.concatenate([pressure_normal, pressure_anomaly])
    vibration = np.concatenate([vibration_normal, vibration_anomaly])
    is_anomaly = np.concatenate([np.zeros(n_normal, dtype=int), np.ones(n_anomaly, dtype=int)])

    # Shuffle
    idx = np.random.permutation(n)
    return pd.DataFrame({
        "temp": temp[idx],
        "pressure": pressure[idx],
        "vibration": vibration[idx],
        "is_anomaly": is_anomaly[idx],
    })
