"""
Solutions — Chapter 11: Large Language Models & Transformers
Generated by Berta AI

Chapter 11 uses notebook-based solutions (problem_set_1_solutions.ipynb,
problem_set_2_solutions.ipynb). This script runs a minimal check so CI
validate-chapters workflow can run without installing transformer-heavy deps.
"""
import sys
from pathlib import Path

chapter_root = Path(__file__).resolve().parent.parent.parent
assert (chapter_root / "README.md").exists(), "Chapter root should contain README.md"
assert (chapter_root / "notebooks").is_dir(), "Chapter should have notebooks/"

print("Chapter 11 structure OK. Full solutions are in problem_set_*_solutions.ipynb.")
sys.exit(0)
