"""
Solutions — Chapter 9: Deep Learning Fundamentals
Generated by Berta AI | Created by Luigi Pascal Rondanini

Complete, runnable solutions for all five exercises.
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

# ===================================================================
# Solution 1 — Implement a Perceptron
# ===================================================================

class Perceptron:
    """Single-layer perceptron for binary classification."""

    def __init__(self, lr=0.01, n_epochs=1000):
        self.lr = lr
        self.n_epochs = n_epochs
        self.weights = None
        self.bias = 0.0

    def _step(self, z):
        return (z >= 0).astype(int)

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0.0

        for _ in range(self.n_epochs):
            for i in range(n_samples):
                z = X[i] @ self.weights + self.bias
                y_hat = self._step(z)
                error = y[i] - y_hat
                self.weights += self.lr * error * X[i]
                self.bias += self.lr * error

    def predict(self, X):
        z = X @ self.weights + self.bias
        return self._step(z)


# ===================================================================
# Solution 2 — Implement Backpropagation for a 2-Layer Network
# ===================================================================

class NeuralNet2Layer:
    """2-layer network (one hidden) with sigmoid activations and BCE loss."""

    def __init__(self, n_input, n_hidden, n_output=1, lr=0.1, seed=42):
        self.lr = lr
        rng = np.random.RandomState(seed)
        self.W1 = rng.randn(n_input, n_hidden) * 0.5
        self.b1 = np.zeros((1, n_hidden))
        self.W2 = rng.randn(n_hidden, n_output) * 0.5
        self.b2 = np.zeros((1, n_output))

    @staticmethod
    def _sigmoid(z):
        return 1.0 / (1.0 + np.exp(-np.clip(z, -500, 500)))

    def forward(self, X):
        self.Z1 = X @ self.W1 + self.b1
        self.A1 = self._sigmoid(self.Z1)
        self.Z2 = self.A1 @ self.W2 + self.b2
        self.A2 = self._sigmoid(self.Z2)
        return self.A2

    def backward(self, X, y):
        m = X.shape[0]
        dZ2 = self.A2 - y
        dW2 = self.A1.T @ dZ2 / m
        db2 = np.mean(dZ2, axis=0, keepdims=True)

        dA1 = dZ2 @ self.W2.T
        dZ1 = dA1 * self.A1 * (1 - self.A1)
        dW1 = X.T @ dZ1 / m
        db1 = np.mean(dZ1, axis=0, keepdims=True)

        self.W2 -= self.lr * dW2
        self.b2 -= self.lr * db2
        self.W1 -= self.lr * dW1
        self.b1 -= self.lr * db1

    def train(self, X, y, epochs=2000, verbose=True):
        y = y.reshape(-1, 1) if y.ndim == 1 else y
        losses = []
        for epoch in range(1, epochs + 1):
            y_hat = self.forward(X)
            eps = 1e-8
            loss = -np.mean(y * np.log(y_hat + eps) + (1 - y) * np.log(1 - y_hat + eps))
            losses.append(loss)
            self.backward(X, y)
            if verbose and epoch % max(1, epochs // 10) == 0:
                print(f"Epoch {epoch:>5d}/{epochs}  Loss: {loss:.6f}")
        return losses


# ===================================================================
# Solution 3 — Build a PyTorch Classifier
# ===================================================================

class _BinaryClassifier(nn.Module):
    def __init__(self, n_input, n_hidden):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_input, n_hidden),
            nn.ReLU(),
            nn.Linear(n_hidden, n_hidden),
            nn.ReLU(),
            nn.Linear(n_hidden, 1),
        )

    def forward(self, x):
        return self.net(x)


def build_and_train_classifier(X, y, n_hidden=16, epochs=500, lr=0.01):
    X_t = torch.tensor(X, dtype=torch.float32)
    y_t = torch.tensor(y, dtype=torch.float32).unsqueeze(1)

    model = _BinaryClassifier(X.shape[1], n_hidden)
    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    loss_history = []
    for epoch in range(1, epochs + 1):
        optimizer.zero_grad()
        logits = model(X_t)
        loss = criterion(logits, y_t)
        loss.backward()
        optimizer.step()
        loss_history.append(loss.item())

    return model, loss_history


# ===================================================================
# Solution 4 — Implement Dropout from Scratch
# ===================================================================

def apply_dropout(A, keep_prob=0.8, seed=None):
    if seed is not None:
        np.random.seed(seed)
    mask = (np.random.rand(*A.shape) < keep_prob).astype(float)
    A_dropped = A * mask / keep_prob
    return A_dropped, mask


# ===================================================================
# Solution 5 — End-to-End CNN Pipeline
# ===================================================================

class _SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 8, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(8 * 4 * 4, 32),
            nn.ReLU(),
            nn.Linear(32, 2),
        )

    def forward(self, x):
        x = self.features(x)
        return self.classifier(x)


def build_cnn_pipeline(n_samples=500, n_epochs=5, seed=42):
    torch.manual_seed(seed)
    np.random.seed(seed)

    X = np.random.randn(n_samples, 1, 8, 8).astype(np.float32)
    y = np.random.randint(0, 2, size=n_samples)
    X[y == 1] += 0.5

    X_t = torch.tensor(X)
    y_t = torch.tensor(y, dtype=torch.long)

    model = _SimpleCNN()
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=1e-3)

    model.train()
    for epoch in range(n_epochs):
        optimizer.zero_grad()
        logits = model(X_t)
        loss = criterion(logits, y_t)
        loss.backward()
        optimizer.step()

    model.eval()
    with torch.no_grad():
        preds = model(X_t).argmax(dim=1)
        accuracy = (preds == y_t).float().mean().item()

    return model, accuracy


# ===================================================================
# Verification
# ===================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("Solution 1 — Perceptron (AND gate)")
    print("=" * 60)
    X_and = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=float)
    y_and = np.array([0, 0, 0, 1])
    p = Perceptron(lr=0.1, n_epochs=100)
    p.fit(X_and, y_and)
    preds = p.predict(X_and)
    print(f"  Predictions: {preds}  (expected [0, 0, 0, 1])")
    print(f"  Accuracy:    {np.mean(preds == y_and) * 100:.0f}%\n")

    print("=" * 60)
    print("Solution 2 — 2-Layer Network (XOR)")
    print("=" * 60)
    X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=float)
    y_xor = np.array([[0], [1], [1], [0]], dtype=float)
    net2 = NeuralNet2Layer(2, 8, 1, lr=1.0, seed=42)
    losses = net2.train(X_xor, y_xor, epochs=5000, verbose=False)
    preds2 = (net2.forward(X_xor) >= 0.5).astype(int)
    print(f"  Predictions: {preds2.ravel()}  (expected [0, 1, 1, 0])")
    print(f"  Final loss:  {losses[-1]:.6f}\n")

    print("=" * 60)
    print("Solution 3 — PyTorch Classifier")
    print("=" * 60)
    from sklearn.datasets import make_moons
    X_m, y_m = make_moons(200, noise=0.2, random_state=42)
    model3, hist3 = build_and_train_classifier(X_m, y_m, epochs=300)
    print(f"  Final loss:  {hist3[-1]:.4f}\n")

    print("=" * 60)
    print("Solution 4 — Dropout from Scratch")
    print("=" * 60)
    A = np.ones((3, 4))
    A_drop, mask = apply_dropout(A, keep_prob=0.5, seed=0)
    print(f"  Original sum:  {A.sum():.1f}")
    print(f"  Dropped sum:   {A_drop.sum():.1f}")
    print(f"  Mask:\n{mask}\n")

    print("=" * 60)
    print("Solution 5 — CNN Pipeline")
    print("=" * 60)
    model5, acc5 = build_cnn_pipeline(n_samples=300, n_epochs=10, seed=42)
    print(f"  Training accuracy: {acc5 * 100:.1f}%")

    print("\nAll solutions verified.")
