"""
Probability & Statistics Toolkit for Berta AI Curriculum

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import random
import math
from typing import List, Tuple


def simulate_coin_flips(n: int, p: float = 0.5) -> List[int]:
    """Simulate n coin flips. Returns list of 0 (tails) and 1 (heads)."""
    return [1 if random.random() < p else 0 for _ in range(n)]


def simulate_dice(n: int, sides: int = 6) -> List[int]:
    """Simulate n dice rolls. Returns list of outcomes 1 to sides."""
    return [random.randint(1, sides) for _ in range(n)]


def normal_pdf(x: float, mu: float = 0.0, sigma: float = 1.0) -> float:
    """Normal PDF from scratch (no scipy): φ(x) = (1/√(2πσ²)) exp(-(x-μ)²/(2σ²))."""
    return (1 / (sigma * math.sqrt(2 * math.pi))) * math.exp(-0.5 * ((x - mu) / sigma) ** 2)


def binomial_pmf(k: int, n: int, p: float) -> float:
    """Binomial PMF from scratch (no scipy): P(X=k) for Bin(n,p)."""
    if k < 0 or k > n:
        return 0.0
    coef = math.factorial(n) / (math.factorial(k) * math.factorial(n - k))
    return coef * (p ** k) * ((1 - p) ** (n - k))


def bayes_update(p_prior: float, p_likelihood: float, p_evidence: float) -> float:
    """Posterior = Likelihood * Prior / Evidence. Returns P(H|E)."""
    if p_evidence <= 0:
        return 0.0
    return (p_likelihood * p_prior) / p_evidence


def confidence_interval(sample: List[float], confidence: float = 0.95) -> Tuple[float, float]:
    """Compute confidence interval for mean. Uses approximate z for n>30."""
    n = len(sample)
    if n == 0:
        return 0.0, 0.0
    mean = sum(sample) / n
    variance = sum((x - mean) ** 2 for x in sample) / (n - 1) if n > 1 else 0.0
    std_err = math.sqrt(variance / n) if n > 0 else 0.0
    # z for 95% = 1.96, 90% = 1.645; approximate for large n
    z = 1.96 if confidence >= 0.95 else 1.645
    h = z * std_err
    return mean - h, mean + h


def ab_test(n_a: int, conv_a: int, n_b: int, conv_b: int) -> Tuple[float, float]:
    """Two-proportion z-test for A/B test. Returns (z_statistic, p_value)."""
    p_a = conv_a / n_a if n_a > 0 else 0.0
    p_b = conv_b / n_b if n_b > 0 else 0.0
    p_pool = (conv_a + conv_b) / (n_a + n_b) if (n_a + n_b) > 0 else 0.0
    se = math.sqrt(p_pool * (1 - p_pool) * (1 / n_a + 1 / n_b)) if (n_a + n_b) > 0 else 0.0
    if se == 0:
        return 0.0, 1.0
    z = (p_a - p_b) / se
    # Two-tailed p-value from normal CDF (approximation)
    p_value = 2 * (1 - _norm_cdf(abs(z)))
    return z, p_value


def _norm_cdf(x: float) -> float:
    """Approximate standard normal CDF (no scipy)."""
    a1, a2, a3, a4, a5 = 0.254829592, -0.284496736, 1.421413741, -1.453152027, 1.061405429
    p = 0.3275911
    t = 1.0 / (1.0 + p * x)
    y = 1.0 - (a1 * t + a2 * t ** 2 + a3 * t ** 3 + a4 * t ** 4 + a5 * t ** 5) * math.exp(-x * x / 2)
    return 0.5 * (1.0 + math.copysign(y, x)) if x >= 0 else 1.0 - _norm_cdf(-x)


def bootstrap_mean(sample: List[float], n_bootstrap: int = 1000, confidence: float = 0.95) -> Tuple[float, float]:
    """Bootstrap confidence interval for the mean."""
    n = len(sample)
    if n == 0:
        return 0.0, 0.0
    means = []
    for _ in range(n_bootstrap):
        resample = [random.choice(sample) for _ in range(n)]
        means.append(sum(resample) / n)
    means.sort()
    alpha = (1 - confidence) / 2
    low_idx = int(alpha * n_bootstrap)
    high_idx = int((1 - alpha) * n_bootstrap)
    return means[low_idx], means[high_idx]


if __name__ == "__main__":
    print("Probability Toolkit - Demo\n")
    print("1. simulate_coin_flips(10):", simulate_coin_flips(10))
    print("2. simulate_dice(5):", simulate_dice(5))
    print("3. normal_pdf(0):", normal_pdf(0))
    print("4. binomial_pmf(5, 10, 0.5):", binomial_pmf(5, 10, 0.5))
    print("5. bayes_update(0.01, 0.95, 0.029):", round(bayes_update(0.01, 0.95, 0.029), 3))
    print("6. confidence_interval([1,2,3,4,5]):", confidence_interval([1, 2, 3, 4, 5]))
    print("7. ab_test(500, 120, 500, 100):", ab_test(500, 120, 500, 100))
    print("8. bootstrap_mean([1,2,3,4,5], 500):", bootstrap_mean([1, 2, 3, 4, 5], 500))
    print("\nAll functions produce valid output. Use matplotlib in notebooks for visualizations.")
