"""
Helper Functions for Probability & Statistics

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import math
from typing import List, Tuple


def mean(x: List[float]) -> float:
    """Sample mean."""
    return sum(x) / len(x) if x else 0.0


def variance(x: List[float], ddof: int = 1) -> float:
    """Sample variance. ddof=1 for sample variance (n-1 denominator)."""
    n = len(x)
    if n <= ddof:
        return 0.0
    m = mean(x)
    return sum((xi - m) ** 2 for xi in x) / (n - ddof)


def std(x: List[float], ddof: int = 1) -> float:
    """Sample standard deviation."""
    return math.sqrt(variance(x, ddof))


def correlation(x: List[float], y: List[float]) -> float:
    """Pearson correlation coefficient between x and y."""
    n = len(x)
    if n != len(y) or n < 2:
        return 0.0
    mx, my = mean(x), mean(y)
    num = sum((xi - mx) * (yi - my) for xi, yi in zip(x, y))
    den = math.sqrt(sum((xi - mx) ** 2 for xi in x) * sum((yi - my) ** 2 for yi in y))
    return num / den if den != 0 else 0.0


def standard_error(sample: List[float]) -> float:
    """Standard error of the mean: σ/√n."""
    n = len(sample)
    if n < 2:
        return 0.0
    return std(sample) / math.sqrt(n)


def odds_ratio(a: int, b: int, c: int, d: int) -> float:
    """Odds ratio for 2x2 table: [[a,b],[c,d]]. Used in categorical A/B analysis."""
    if b == 0 or d == 0:
        return 0.0
    return (a * d) / (b * c)


def relative_risk(p1: float, p2: float) -> float:
    """Relative risk: p1/p2. p1, p2 are proportions."""
    return p1 / p2 if p2 != 0 else 0.0


if __name__ == "__main__":
    print("Stats Utilities - Demo\n")
    data = [1.0, 2.0, 3.0, 4.0, 5.0]
    print("mean:", mean(data))
    print("variance:", variance(data))
    print("std:", std(data))
    print("standard_error:", standard_error(data))
    x, y = [1, 2, 3, 4, 5], [2, 4, 5, 4, 5]
    print("correlation:", correlation(x, y))
