"""
Chapter 6 Solutions: Introduction to Machine Learning

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


def train_test_split_scratch(X, y, test_ratio=0.2, random_state=None):
    """Return (X_train, X_test, y_train, y_test)."""
    if random_state is not None:
        np.random.seed(random_state)
    X = np.asarray(X)
    y = np.asarray(y)
    n = len(X)
    indices = np.random.permutation(n)
    split = int(n * (1 - test_ratio))
    train_idx, test_idx = indices[:split], indices[split:]
    return X[train_idx], X[test_idx], y[train_idx], y[test_idx]


def confusion_metrics(tp, fp, fn, tn):
    """Return {'precision': ..., 'recall': ..., 'f1': ...}."""
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    return {"precision": precision, "recall": recall, "f1": f1}


def k_fold_cv(X, y, model, k=5, score_fn=None, random_state=42):
    """Return (mean_score, std_score)."""
    if score_fn is None:
        def score_fn(yt, yp):
            return -np.mean((np.array(yt) - np.array(yp)) ** 2)  # neg MSE
    np.random.seed(random_state)
    X = np.asarray(X)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    y = np.asarray(y)
    n = len(y)
    indices = np.random.permutation(n)
    fold_size = n // k
    scores = []
    for i in range(k):
        start = i * fold_size
        end = (i + 1) * fold_size if i < k - 1 else n
        val_idx = indices[start:end]
        train_idx = np.concatenate([indices[:start], indices[end:]]) if end < n else indices[:start]
        if len(train_idx) == 0:
            train_idx = indices[end:]
        X_train, X_val = X[train_idx], X[val_idx]
        y_train, y_val = y[train_idx], y[val_idx]
        from sklearn.base import clone
        model_clone = clone(model)
        model_clone.fit(X_train, y_train)
        y_pred = model_clone.predict(X_val)
        scores.append(score_fn(y_val, y_pred))
    return float(np.mean(scores)), float(np.std(scores)) if len(scores) > 1 else 0.0


def build_pipeline(filepath, target_col, feature_cols, random_state=42):
    """Return evaluation metrics dict."""
    df = pd.read_csv(filepath)
    X = df[feature_cols].copy()
    y = df[target_col]
    y_str = y.astype(str).str.upper()
    if set(y_str.unique()) <= {"YES", "NO"}:
        y = (y_str == "YES").astype(int)
    else:
        y = y.astype(int)
    for col in X.select_dtypes(include=["object"]).columns:
        X[col] = LabelEncoder().fit_transform(X[col].astype(str))
    X = X.fillna(X.median())
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=random_state, stratify=y if len(np.unique(y)) > 1 else None
    )
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    model = LogisticRegression(max_iter=1000, random_state=random_state)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    return {
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred, zero_division=0),
        "recall": recall_score(y_test, y_pred, zero_division=0),
        "f1": f1_score(y_test, y_pred, zero_division=0),
    }


def compare_models_on_dataset(filepath, target_col, feature_cols, models):
    """Return list of dicts sorted by F1 desc."""
    df = pd.read_csv(filepath)
    X = df[feature_cols].copy()
    y = df[target_col]
    y_str = y.astype(str).str.upper()
    if set(y_str.unique()) <= {"YES", "NO"}:
        y = (y_str == "YES").astype(int)
    else:
        y = y.astype(int)
    for col in X.select_dtypes(include=["object"]).columns:
        X[col] = LabelEncoder().fit_transform(X[col].astype(str))
    X = X.fillna(X.median())
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    results = []
    for name, model in models:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        results.append({
            "model": name,
            "accuracy": accuracy_score(y_test, y_pred),
            "f1": f1_score(y_test, y_pred, zero_division=0),
        })
    return sorted(results, key=lambda x: x["f1"], reverse=True)


if __name__ == "__main__":
    print("Chapter 6 Solutions - Verification\n")

    # Ex 1
    print("Exercise 1: Train/Test Split")
    X, y = list(range(20)), list(range(20))
    X_train, X_test, y_train, y_test = train_test_split_scratch(X, y, 0.2, 42)
    assert len(X_train) == 16 and len(X_test) == 4
    print("  OK")

    # Ex 2
    print("Exercise 2: Confusion Metrics")
    m = confusion_metrics(8, 2, 1, 9)
    assert abs(m["precision"] - 0.8) < 1e-6
    assert abs(m["recall"] - 8/9) < 1e-6
    print("  OK:", m)

    # Ex 3
    print("Exercise 3: K-Fold CV")
    np.random.seed(42)
    X = np.random.randn(100, 2)
    y = X[:, 0] + X[:, 1] + np.random.randn(100) * 0.1
    from sklearn.linear_model import LinearRegression
    mean_s, std_s = k_fold_cv(X, y, LinearRegression(), k=5)
    assert isinstance(mean_s, (float, np.floating)) and isinstance(std_s, (float, np.floating))
    print("  OK: mean=", mean_s, "std=", std_s)

    # Ex 4 & 5 require datasets/customers.csv
    import os
    data_path = os.path.join(os.path.dirname(__file__), "..", "..", "datasets", "customers.csv")
    if os.path.exists(data_path):
        print("Exercise 4: Build Pipeline")
        metrics = build_pipeline(
            data_path,
            "churn",
            ["age", "income", "tenure", "monthly_charges", "total_charges", "contract_type"],
        )
        print("  OK:", metrics)
        print("Exercise 5: Compare Models")
        models = [
            ("Logistic Regression", LogisticRegression(max_iter=1000)),
            ("Decision Tree", DecisionTreeClassifier()),
            ("Random Forest", RandomForestClassifier(n_estimators=50)),
        ]
        res = compare_models_on_dataset(
            data_path, "churn",
            ["age", "income", "tenure", "monthly_charges", "total_charges", "contract_type"],
            models,
        )
        print("  OK:", res)
    else:
        print("Skipping Ex 4 & 5 (customers.csv not found)")

    print("\nAll verifications passed.")
