"""
Deep Learning Toolkit — Chapter 9: Deep Learning Fundamentals
Generated by Berta AI | Created by Luigi Pascal Rondanini

Production toolkit implementing neural networks from scratch with NumPy,
activation functions, and visualization utilities.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ---------------------------------------------------------------------------
# Activation functions (standalone)
# ---------------------------------------------------------------------------

def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-np.clip(z, -500, 500)))


def sigmoid_derivative(z):
    s = sigmoid(z)
    return s * (1.0 - s)


def relu(z):
    return np.maximum(0, z)


def relu_derivative(z):
    return (z > 0).astype(float)


def tanh(z):
    return np.tanh(z)


def tanh_derivative(z):
    return 1.0 - np.tanh(z) ** 2


# ---------------------------------------------------------------------------
# Neural Network from Scratch (NumPy only)
# ---------------------------------------------------------------------------

class NeuralNetScratch:
    """Fully-connected neural network built with pure NumPy."""

    _activations = {
        "relu": (relu, relu_derivative),
        "sigmoid": (sigmoid, sigmoid_derivative),
        "tanh": (tanh, tanh_derivative),
    }

    def __init__(self, layer_sizes, activation="relu", seed=42):
        """
        Parameters
        ----------
        layer_sizes : list[int]
            Number of neurons in each layer, e.g. [2, 8, 4, 1].
        activation : str
            Hidden-layer activation: 'relu', 'sigmoid', or 'tanh'.
        seed : int
            Random seed for reproducibility.
        """
        self.layer_sizes = layer_sizes
        self.activation_name = activation
        self.act_fn, self.act_deriv = self._activations[activation]
        self.num_layers = len(layer_sizes) - 1

        rng = np.random.RandomState(seed)
        self.weights = []
        self.biases = []
        for i in range(self.num_layers):
            fan_in, fan_out = layer_sizes[i], layer_sizes[i + 1]
            scale = np.sqrt(2.0 / fan_in)
            self.weights.append(rng.randn(fan_in, fan_out) * scale)
            self.biases.append(np.zeros((1, fan_out)))

        self.A_cache = []
        self.Z_cache = []
        self.loss_history = []

    def forward(self, X):
        """Forward pass — stores all activations (A) and pre-activations (Z)."""
        self.A_cache = [X]
        self.Z_cache = []
        A = X
        for i in range(self.num_layers):
            Z = A @ self.weights[i] + self.biases[i]
            self.Z_cache.append(Z)
            if i == self.num_layers - 1:
                A = sigmoid(Z)  # output layer always sigmoid
            else:
                A = self.act_fn(Z)
            self.A_cache.append(A)
        return A

    def _compute_loss(self, y_hat, y):
        m = y.shape[0]
        eps = 1e-8
        y_hat = np.clip(y_hat, eps, 1 - eps)
        return -np.mean(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    def backward(self, X, y, lr=0.01):
        """Backpropagation with chain rule; updates weights in-place."""
        m = X.shape[0]
        y = y.reshape(-1, 1) if y.ndim == 1 else y

        dA = self.A_cache[-1] - y  # derivative of BCE + sigmoid
        for i in reversed(range(self.num_layers)):
            if i == self.num_layers - 1:
                dZ = dA
            else:
                dZ = dA * self.act_deriv(self.Z_cache[i])

            dW = self.A_cache[i].T @ dZ / m
            db = np.mean(dZ, axis=0, keepdims=True)
            dA = dZ @ self.weights[i].T

            self.weights[i] -= lr * dW
            self.biases[i] -= lr * db

    def train(self, X, y, epochs=1000, lr=0.01, batch_size=None, verbose=True):
        """
        Training loop with optional mini-batch support.

        Returns
        -------
        list[float]
            Loss at each epoch.
        """
        y_col = y.reshape(-1, 1) if y.ndim == 1 else y
        m = X.shape[0]
        self.loss_history = []

        for epoch in range(1, epochs + 1):
            if batch_size is None:
                y_hat = self.forward(X)
                self.backward(X, y_col, lr)
                loss = self._compute_loss(y_hat, y_col)
            else:
                indices = np.random.permutation(m)
                epoch_loss = 0.0
                n_batches = 0
                for start in range(0, m, batch_size):
                    end = min(start + batch_size, m)
                    idx = indices[start:end]
                    Xb, yb = X[idx], y_col[idx]
                    y_hat = self.forward(Xb)
                    self.backward(Xb, yb, lr)
                    epoch_loss += self._compute_loss(y_hat, yb)
                    n_batches += 1
                loss = epoch_loss / n_batches

            self.loss_history.append(loss)
            if verbose and epoch % max(1, epochs // 10) == 0:
                print(f"Epoch {epoch:>5d}/{epochs}  Loss: {loss:.6f}")

        return self.loss_history

    def predict(self, X):
        """Forward pass + threshold at 0.5 for binary classification."""
        probs = self.forward(X)
        return (probs >= 0.5).astype(int)


# ---------------------------------------------------------------------------
# Plotting utilities
# ---------------------------------------------------------------------------

def plot_loss_curve(history, title="Training Loss"):
    """Plot training loss over epochs."""
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(history, linewidth=2, color="#2563eb")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss")
    ax.set_title(title)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    return fig


def plot_decision_boundary_nn(model, X, y, title="Decision Boundary", resolution=200):
    """Visualise the decision surface of a NeuralNetScratch model."""
    x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
    y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
    xx, yy = np.meshgrid(
        np.linspace(x_min, x_max, resolution),
        np.linspace(y_min, y_max, resolution),
    )
    grid = np.c_[xx.ravel(), yy.ravel()]
    preds = model.predict(grid).reshape(xx.shape)

    fig, ax = plt.subplots(figsize=(7, 6))
    ax.contourf(xx, yy, preds, levels=[0, 0.5, 1], alpha=0.3, colors=["#93c5fd", "#fca5a5"])
    ax.scatter(X[:, 0], X[:, 1], c=y.ravel(), cmap="bwr", edgecolors="k", s=20, linewidths=0.5)
    ax.set_title(title)
    ax.set_xlabel("x₁")
    ax.set_ylabel("x₂")
    fig.tight_layout()
    return fig


def plot_activations(activations_list=None, title="Activation Functions"):
    """Plot sigmoid, relu, and tanh on a single figure."""
    z = np.linspace(-5, 5, 300)
    funcs = [("Sigmoid", sigmoid), ("ReLU", relu), ("Tanh", tanh)]

    fig, ax = plt.subplots(figsize=(8, 5))
    colors = ["#2563eb", "#dc2626", "#16a34a"]
    for (name, fn), color in zip(funcs, colors):
        ax.plot(z, fn(z), label=name, linewidth=2, color=color)
    ax.axhline(0, color="grey", linewidth=0.5)
    ax.axvline(0, color="grey", linewidth=0.5)
    ax.set_title(title)
    ax.set_xlabel("z")
    ax.set_ylabel("f(z)")
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    return fig


def plot_network_architecture(layer_sizes, title="Network Architecture"):
    """Draw a simple network diagram with circles and lines."""
    fig, ax = plt.subplots(figsize=(10, 6))
    n_layers = len(layer_sizes)
    max_neurons = max(layer_sizes)
    x_spacing = 1.0 / (n_layers + 1)
    node_radius = 0.02

    positions = []
    for i, size in enumerate(layer_sizes):
        layer_x = (i + 1) * x_spacing
        layer_positions = []
        y_offset = 0.5
        y_spacing = 0.8 / (size + 1) if size > 1 else 0
        for j in range(size):
            y = y_offset - 0.4 + (j + 1) * y_spacing if size > 1 else y_offset
            layer_positions.append((layer_x, y))
        positions.append(layer_positions)

    for i in range(n_layers - 1):
        for x1, y1 in positions[i]:
            for x2, y2 in positions[i + 1]:
                ax.plot([x1, x2], [y1, y2], "grey", linewidth=0.5, alpha=0.5)

    layer_labels = (
        ["Input"]
        + [f"Hidden {i}" for i in range(1, n_layers - 1)]
        + ["Output"]
    )
    colors = ["#60a5fa"] + ["#a78bfa"] * (n_layers - 2) + ["#f87171"]
    for i, (layer_pos, color) in enumerate(zip(positions, colors)):
        for x, y in layer_pos:
            circle = plt.Circle((x, y), node_radius, color=color, ec="k", lw=0.8, zorder=3)
            ax.add_patch(circle)
        mid_y = np.mean([p[1] for p in layer_pos])
        ax.text(
            layer_pos[0][0], -0.02, f"{layer_labels[i]}\n({layer_sizes[i]})",
            ha="center", va="top", fontsize=9,
        )

    ax.set_xlim(0, 1)
    ax.set_ylim(-0.1, 1.0)
    ax.set_aspect("equal")
    ax.set_title(title)
    ax.axis("off")
    fig.tight_layout()
    return fig


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    np.random.seed(42)
    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=float)
    y = np.array([[0], [1], [1], [0]], dtype=float)

    nn = NeuralNetScratch([2, 4, 1], activation="relu", seed=42)
    nn.train(X, y, epochs=5000, lr=0.1, verbose=True)

    preds = nn.predict(X)
    accuracy = np.mean(preds == y) * 100
    print(f"\nXOR Accuracy: {accuracy:.1f}%")
    print("Demo complete.")
