"""
Utilities — Chapter 9: Deep Learning Fundamentals
Generated by Berta AI | Created by Luigi Pascal Rondanini

Helper functions for data generation and persistence.
"""

import numpy as np
import csv
import os


def generate_spiral_data(n_points=500, n_classes=2, seed=42):
    """
    Generate a 2-D spiral dataset.

    Parameters
    ----------
    n_points : int
        Total number of points (split evenly across classes).
    n_classes : int
        Number of spiral arms / classes.
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    X : np.ndarray, shape (n_points, 2)
    y : np.ndarray, shape (n_points,)
    """
    rng = np.random.RandomState(seed)
    points_per_class = n_points // n_classes
    X = np.zeros((n_points, 2))
    y = np.zeros(n_points, dtype=int)

    for cls in range(n_classes):
        ix = range(points_per_class * cls, points_per_class * (cls + 1))
        r = np.linspace(0.0, 1.0, points_per_class)
        t = (
            np.linspace(cls * 4, (cls + 1) * 4, points_per_class)
            + rng.randn(points_per_class) * 0.2
        )
        X[ix] = np.c_[r * np.sin(t), r * np.cos(t)]
        y[ix] = cls

    return X, y


def generate_sine_sequence(n_points=200, seq_length=20, seed=42):
    """
    Generate sine-wave sequences suitable for RNN training.

    Parameters
    ----------
    n_points : int
        Number of raw sine values to sample.
    seq_length : int
        Length of each input sequence.
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    sequences : np.ndarray, shape (n_samples, seq_length, 1)
    targets : np.ndarray, shape (n_samples, 1)
        The next value after each sequence.
    """
    rng = np.random.RandomState(seed)
    t = np.linspace(0, 4 * np.pi, n_points)
    signal = np.sin(t) + rng.randn(n_points) * 0.05

    sequences, targets = [], []
    for i in range(len(signal) - seq_length):
        sequences.append(signal[i : i + seq_length])
        targets.append(signal[i + seq_length])

    sequences = np.array(sequences)[..., np.newaxis]
    targets = np.array(targets)[..., np.newaxis]
    return sequences, targets


def save_spiral_csv(path, n_points=500):
    """
    Generate spiral data and save to CSV with columns x1, x2, label.

    Parameters
    ----------
    path : str
        Destination file path.
    n_points : int
        Total number of points.
    """
    X, y = generate_spiral_data(n_points=n_points)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["x1", "x2", "label"])
        for i in range(X.shape[0]):
            writer.writerow([X[i, 0], X[i, 1], y[i]])
    print(f"Saved {n_points} spiral points to {path}")
