"""
Chapter 8 Solutions: Unsupervised Learning

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
from pathlib import Path


# =============================================================================
# Exercise 1: K-Means Clustering From Scratch
# =============================================================================

class KMeansClustering:
    def __init__(self, n_clusters=3, max_iters=100, random_state=42):
        self.n_clusters = n_clusters
        self.max_iters = max_iters
        self.random_state = random_state
        self.centroids = None
        self.inertia = None

    def fit(self, X):
        X = np.asarray(X, dtype=float)
        rng = np.random.RandomState(self.random_state)
        idx = rng.choice(len(X), size=self.n_clusters, replace=False)
        self.centroids = X[idx].copy()

        for _ in range(self.max_iters):
            distances = np.linalg.norm(X[:, None] - self.centroids, axis=2)
            labels = np.argmin(distances, axis=1)

            new_centroids = np.array([
                X[labels == k].mean(axis=0) if np.any(labels == k) else self.centroids[k]
                for k in range(self.n_clusters)
            ])

            if np.allclose(new_centroids, self.centroids):
                break
            self.centroids = new_centroids

        distances = np.linalg.norm(X[:, None] - self.centroids, axis=2)
        labels = np.argmin(distances, axis=1)
        self.inertia = sum(
            np.sum((X[labels == k] - self.centroids[k]) ** 2)
            for k in range(self.n_clusters)
        )
        self._labels = labels
        return self

    def predict(self, X):
        X = np.asarray(X, dtype=float)
        distances = np.linalg.norm(X[:, None] - self.centroids, axis=2)
        return np.argmin(distances, axis=1)

    def fit_predict(self, X):
        self.fit(X)
        return self._labels


# =============================================================================
# Exercise 2: PCA From Scratch
# =============================================================================

class PCAFromScratch:
    def __init__(self, n_components=2):
        self.n_components = n_components
        self.components_ = None
        self.explained_variance_ratio_ = None
        self._mean = None

    def fit(self, X):
        X = np.asarray(X, dtype=float)
        self._mean = X.mean(axis=0)
        X_centered = X - self._mean
        n = X.shape[0]
        cov = X_centered.T @ X_centered / (n - 1)

        eigenvalues, eigenvectors = np.linalg.eigh(cov)
        idx = np.argsort(eigenvalues)[::-1]
        eigenvalues = eigenvalues[idx]
        eigenvectors = eigenvectors[:, idx]

        self.components_ = eigenvectors[:, :self.n_components].T
        total_var = eigenvalues.sum()
        self.explained_variance_ratio_ = eigenvalues[:self.n_components] / total_var
        return self

    def transform(self, X):
        X = np.asarray(X, dtype=float)
        X_centered = X - self._mean
        return X_centered @ self.components_.T

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)


# =============================================================================
# Exercise 3: Silhouette Score From Scratch
# =============================================================================

def silhouette_score_scratch(X, labels):
    X = np.asarray(X, dtype=float)
    labels = np.asarray(labels)
    n = len(X)
    unique_labels = np.unique(labels)

    if len(unique_labels) < 2:
        return 0.0

    scores = np.zeros(n)
    for i in range(n):
        same_mask = labels == labels[i]
        same_mask[i] = False
        same_cluster = X[same_mask]

        if len(same_cluster) == 0:
            scores[i] = 0.0
            continue

        a_i = np.mean(np.linalg.norm(same_cluster - X[i], axis=1))

        b_i = np.inf
        for k in unique_labels:
            if k == labels[i]:
                continue
            other_cluster = X[labels == k]
            mean_dist = np.mean(np.linalg.norm(other_cluster - X[i], axis=1))
            b_i = min(b_i, mean_dist)

        denom = max(a_i, b_i)
        scores[i] = (b_i - a_i) / denom if denom > 0 else 0.0

    return float(np.mean(scores))


# =============================================================================
# Exercise 4: Anomaly Detection with Z-Score
# =============================================================================

def detect_anomalies_zscore(X, threshold=3.0):
    X = np.asarray(X, dtype=float)
    mean = X.mean(axis=0)
    std = X.std(axis=0)
    std[std == 0] = 1.0
    z_scores = (X - mean) / std
    return np.any(np.abs(z_scores) > threshold, axis=1)


# =============================================================================
# Exercise 5: Customer Segmentation Pipeline
# =============================================================================

def customer_segmentation_pipeline(csv_path="datasets/customers.csv"):
    try:
        import pandas as pd
        from sklearn.preprocessing import StandardScaler
        from sklearn.decomposition import PCA
        from sklearn.cluster import KMeans
        from sklearn.metrics import silhouette_score
    except ImportError:
        return {"n_clusters": 0, "labels": None, "profiles": None,
                "inertias": [], "silhouette": 0.0}

    base = Path(__file__).parent.parent.parent
    path = base / csv_path
    if not path.exists():
        return {"n_clusters": 0, "labels": None, "profiles": None,
                "inertias": [], "silhouette": 0.0}

    df = pd.read_csv(path)
    feature_cols = [c for c in df.columns if c not in ("customer_id", "segment")]
    X_raw = df[feature_cols].values

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_raw)

    pca = PCA(n_components=0.95)
    X_pca = pca.fit_transform(X_scaled)

    K_range = range(2, 9)
    inertias = []
    for k in K_range:
        km = KMeans(n_clusters=k, n_init=10, random_state=42)
        km.fit(X_pca)
        inertias.append(km.inertia_)

    diffs = np.diff(inertias)
    diffs2 = np.diff(diffs)
    best_k = int(np.argmax(np.abs(diffs2)) + 2)
    best_k = max(2, min(best_k, 8))

    km_final = KMeans(n_clusters=best_k, n_init=10, random_state=42)
    labels = km_final.fit_predict(X_pca)
    sil = silhouette_score(X_pca, labels)

    df["cluster"] = labels
    profiles = df.groupby("cluster")[feature_cols].mean()

    return {
        "n_clusters": best_k,
        "labels": labels,
        "profiles": profiles,
        "inertias": list(inertias),
        "silhouette": float(sil),
    }


if __name__ == "__main__":
    print("Chapter 8 Solutions - Verification\n")

    np.random.seed(42)

    # Ex 1
    print("Exercise 1: K-Means Clustering")
    from sklearn.datasets import make_blobs
    X, y_true = make_blobs(n_samples=200, centers=3, random_state=42)
    km = KMeansClustering(n_clusters=3, random_state=42)
    labels = km.fit_predict(X)
    assert km.centroids.shape == (3, 2)
    assert len(labels) == 200
    assert km.inertia > 0
    print(f"  Inertia = {km.inertia:.2f}")
    print(f"  Centroids shape: {km.centroids.shape}")

    # Ex 2
    print("\nExercise 2: PCA From Scratch")
    X_4d = np.random.randn(100, 4)
    pca = PCAFromScratch(n_components=2)
    X_2d = pca.fit_transform(X_4d)
    assert X_2d.shape == (100, 2)
    assert len(pca.explained_variance_ratio_) == 2
    assert abs(sum(pca.explained_variance_ratio_) - sum(pca.explained_variance_ratio_)) < 1e-10
    print(f"  Variance explained: {pca.explained_variance_ratio_}")
    print(f"  Projected shape: {X_2d.shape}")

    # Ex 3
    print("\nExercise 3: Silhouette Score")
    sil = silhouette_score_scratch(X, y_true)
    assert -1 <= sil <= 1
    print(f"  Silhouette score = {sil:.4f}")

    # Ex 4
    print("\nExercise 4: Anomaly Detection (Z-Score)")
    X_normal = np.random.randn(100, 3)
    X_anomalies = np.array([[10, 10, 10], [-8, -8, -8]])
    X_combined = np.vstack([X_normal, X_anomalies])
    flags = detect_anomalies_zscore(X_combined, threshold=3.0)
    assert flags[-1] == True
    assert flags[-2] == True
    n_detected = flags.sum()
    print(f"  Detected {n_detected} anomalies out of {len(X_combined)} points")

    # Ex 5
    print("\nExercise 5: Customer Segmentation Pipeline")
    result = customer_segmentation_pipeline()
    if result["labels"] is not None:
        print(f"  Optimal K: {result['n_clusters']}")
        print(f"  Silhouette: {result['silhouette']:.4f}")
        print(f"  Segment profiles:\n{result['profiles']}")
    else:
        print("  (Dataset may not be found - run from chapter root)")

    print("\nAll verifications passed.")
