"""
Chapter 2 Solutions: Data Structures & Algorithms

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import heapq
import math
from collections import OrderedDict


# Exercise 1: Queue from Two Stacks
class QueueFromStacks:
    def __init__(self):
        self.in_stack = []
        self.out_stack = []

    def enqueue(self, item):
        self.in_stack.append(item)

    def dequeue(self):
        if not self.out_stack:
            while self.in_stack:
                self.out_stack.append(self.in_stack.pop())
        if not self.out_stack:
            raise IndexError("Dequeue from empty queue")
        return self.out_stack.pop()


# Exercise 2: K Closest Points
def k_closest(points, target, k):
    tx, ty = target
    distances = []
    for point in points:
        px, py = point
        dist = math.sqrt((px - tx) ** 2 + (py - ty) ** 2)
        distances.append((dist, point))
    return [p for _, p in heapq.nsmallest(k, distances)]


# Exercise 3: Longest Common Subsequence
def lcs(s1, s2):
    m, n = len(s1), len(s2)
    dp = [[0] * (n + 1) for _ in range(m + 1)]

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if s1[i - 1] == s2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1] + 1
            else:
                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])

    return dp[m][n]


# Exercise 4: Cycle Detection
def has_cycle(graph):
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {node: WHITE for node in graph}

    def dfs(node):
        color[node] = GRAY
        for neighbor in graph.get(node, []):
            if color.get(neighbor, WHITE) == GRAY:
                return True
            if color.get(neighbor, WHITE) == WHITE and dfs(neighbor):
                return True
        color[node] = BLACK
        return False

    return any(color[node] == WHITE and dfs(node) for node in graph)


# Exercise 5: LRU Cache
class LRUCache:
    def __init__(self, capacity):
        self.capacity = capacity
        self.cache = OrderedDict()

    def get(self, key):
        if key not in self.cache:
            return -1
        self.cache.move_to_end(key)
        return self.cache[key]

    def put(self, key, value):
        if key in self.cache:
            self.cache.move_to_end(key)
        self.cache[key] = value
        if len(self.cache) > self.capacity:
            self.cache.popitem(last=False)


if __name__ == "__main__":
    print("Chapter 2 Solutions - Verification\n")

    # Ex 1
    print("Exercise 1: Queue from Stacks")
    q = QueueFromStacks()
    for i in range(5):
        q.enqueue(i)
    result = [q.dequeue() for _ in range(5)]
    print(f"  Enqueued 0-4, dequeued: {result}")
    assert result == [0, 1, 2, 3, 4]

    # Ex 2
    print("\nExercise 2: K Closest Points")
    points = [(1, 1), (3, 3), (2, 2), (5, 5), (0, 0)]
    result = k_closest(points, target=(2, 2), k=3)
    print(f"  3 closest to (2,2): {result}")

    # Ex 3
    print("\nExercise 3: LCS")
    for s1, s2 in [("machine", "aching"), ("abcde", "ace"), ("abc", "xyz")]:
        print(f"  lcs('{s1}', '{s2}') = {lcs(s1, s2)}")

    # Ex 4
    print("\nExercise 4: Cycle Detection")
    print(f"  Cyclic graph:  {has_cycle({'a': ['b'], 'b': ['c'], 'c': ['a']})}")
    print(f"  Acyclic graph: {has_cycle({'a': ['b'], 'b': ['c'], 'c': []})}")

    # Ex 5
    print("\nExercise 5: LRU Cache")
    cache = LRUCache(3)
    cache.put("a", 1)
    cache.put("b", 2)
    cache.put("c", 3)
    print(f"  get('a') = {cache.get('a')}")
    cache.put("d", 4)
    print(f"  After adding 'd', get('b') = {cache.get('b')} (evicted)")

    print("\nAll solutions verified!")
