"""
Supervised Learning Toolkit: Regression & Classification

Core implementations and plotting utilities for the Berta AI supervised learning curriculum.

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, precision_recall_curve
from sklearn.preprocessing import StandardScaler


# =============================================================================
# Linear Regression From Scratch
# =============================================================================

class LinearRegressionScratch:
    """Linear regression using normal equation or gradient descent."""

    def __init__(self, method="normal", learning_rate=0.01, epochs=1000):
        self.method = method
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.intercept = None
        self.history = []

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y).ravel()
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        n_samples, n_features = X.shape
        X_b = np.c_[np.ones((n_samples, 1)), X]

        if self.method == "normal":
            self.weights = np.linalg.lstsq(X_b.T @ X_b, X_b.T @ y, rcond=None)[0]
            self.intercept = self.weights[0]
            self.weights = self.weights[1:]
        else:
            self.weights = np.zeros(n_features)
            self.intercept = 0.0
            for _ in range(self.epochs):
                pred = X_b @ np.concatenate([[self.intercept], self.weights])
                errors = pred - y
                grad = X_b.T @ errors / n_samples
                self.intercept -= self.learning_rate * grad[0]
                self.weights -= self.learning_rate * grad[1:]
                mse = np.mean(errors ** 2)
                self.history.append(mse)
        return self

    def predict(self, X):
        X = np.asarray(X)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        return X @ self.weights + self.intercept

    def score(self, X, y):
        y_pred = self.predict(X)
        ss_res = np.sum((y - y_pred) ** 2)
        ss_tot = np.sum((y - np.mean(y)) ** 2)
        if ss_tot == 0:
            return 0.0
        return 1 - ss_res / ss_tot


# =============================================================================
# Logistic Regression From Scratch
# =============================================================================

class LogisticRegressionScratch:
    """Binary logistic regression using gradient descent."""

    def __init__(self, learning_rate=0.1, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.intercept = None

    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-np.clip(z, -500, 500)))

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y).ravel()
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.intercept = 0.0

        for _ in range(self.epochs):
            logits = X @ self.weights + self.intercept
            probs = self._sigmoid(logits)
            errors = probs - y
            grad_w = X.T @ errors / n_samples
            grad_b = np.mean(errors)
            self.weights -= self.learning_rate * grad_w
            self.intercept -= self.learning_rate * grad_b
        return self

    def predict_proba(self, X):
        X = np.asarray(X)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        logits = X @ self.weights + self.intercept
        return self._sigmoid(logits)

    def predict(self, X, threshold=0.5):
        return (self.predict_proba(X) >= threshold).astype(int)


# =============================================================================
# Plotting Functions
# =============================================================================

def plot_decision_boundary(model, X, y, title="Decision Boundary", resolution=200):
    """Plot 2D decision boundary for a binary classifier."""
    X = np.asarray(X)
    y = np.asarray(y)
    if X.shape[1] != 2:
        raise ValueError("plot_decision_boundary requires 2 features")
    x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
    y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, resolution),
                         np.linspace(y_min, y_max, resolution))
    if hasattr(model, 'predict_proba'):
        Z = model.predict_proba(np.c_[xx.ravel(), yy.ravel()])[:, 1]
    else:
        Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    plt.figure(figsize=(8, 6))
    plt.contourf(xx, yy, Z, alpha=0.4, cmap="RdYlBu_r", levels=20)
    plt.contour(xx, yy, Z, levels=[0.5], colors="black", linewidths=2)
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap="RdYlBu_r", edgecolors="black", s=50)
    plt.xlabel("Feature 1")
    plt.ylabel("Feature 2")
    plt.title(title)
    plt.colorbar(label="Predicted probability")
    plt.tight_layout()
    return plt.gca()


def plot_roc_curve(y_true, y_proba, title="ROC Curve", label="Model"):
    """Plot ROC curve with AUC."""
    fpr, tpr, _ = roc_curve(y_true, y_proba)
    roc_auc = auc(fpr, tpr)
    plt.figure(figsize=(6, 5))
    plt.plot(fpr, tpr, color="darkorange", lw=2, label=f"{label} (AUC = {roc_auc:.3f})")
    plt.plot([0, 1], [0, 1], color="navy", lw=2, linestyle="--")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(title)
    plt.legend(loc="lower right")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    return plt.gca(), roc_auc


def plot_residuals(y_true, y_pred, title="Residual Plot"):
    """Plot residuals for regression evaluation."""
    residuals = y_true - y_pred
    plt.figure(figsize=(8, 4))
    plt.subplot(1, 2, 1)
    plt.scatter(y_pred, residuals, alpha=0.6)
    plt.axhline(0, color="red", linestyle="--")
    plt.xlabel("Predicted values")
    plt.ylabel("Residuals")
    plt.title(f"{title} - Residuals vs Predicted")
    plt.subplot(1, 2, 2)
    plt.hist(residuals, bins=25, edgecolor="black", alpha=0.7)
    plt.xlabel("Residual")
    plt.ylabel("Frequency")
    plt.title("Residual Distribution")
    plt.tight_layout()
    return plt.gca()


def plot_regularization_path(alphas, coefs, feature_names=None, title="Regularization Path"):
    """Plot coefficient paths vs regularization strength."""
    plt.figure(figsize=(8, 5))
    for i in range(coefs.shape[1]):
        label = feature_names[i] if feature_names else f"Coef {i}"
        plt.plot(alphas, coefs[:, i], label=label, lw=2)
    plt.xscale("log")
    plt.xlabel("Regularization strength (α)")
    plt.ylabel("Coefficient value")
    plt.title(title)
    plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    return plt.gca()


def plot_feature_importance(importances, feature_names, title="Feature Importance", top_n=15):
    """Bar plot of feature importances."""
    idx = np.argsort(importances)[::-1][:top_n]
    imp = importances[idx]
    names = [feature_names[i] for i in idx] if feature_names else [f"Feature {i}" for i in idx]
    plt.figure(figsize=(8, max(5, len(names) * 0.3)))
    plt.barh(range(len(names)), imp, color="steelblue", alpha=0.8)
    plt.yticks(range(len(names)), names)
    plt.xlabel("Importance")
    plt.title(title)
    plt.gca().invert_yaxis()
    plt.tight_layout()
    return plt.gca()


def compare_regressors(X, y, models, model_names, scoring="r2"):
    """Compare multiple regression models."""
    from sklearn.model_selection import cross_val_score
    results = {}
    for name, model in zip(model_names, models):
        scores = cross_val_score(model, X, y, cv=5, scoring=scoring)
        results[name] = scores
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.boxplot([results[n] for n in model_names], labels=model_names, patch_artist=True)
    ax.set_ylabel(scoring.upper())
    ax.set_title("Regression Model Comparison")
    plt.tight_layout()
    return plt.gca(), results


def compare_classifiers(X, y, models, model_names, cv=5):
    """Compare multiple classifiers with ROC curves (binary only)."""
    from sklearn.model_selection import cross_val_predict
    fig, ax = plt.subplots(figsize=(6, 5))
    for name, model in zip(model_names, models):
        y_proba = cross_val_predict(model, X, y, cv=cv, method="predict_proba")[:, 1]
        fpr, tpr, _ = roc_curve(y, y_proba)
        roc_auc = auc(fpr, tpr)
        ax.plot(fpr, tpr, lw=2, label=f"{name} (AUC={roc_auc:.3f})")
    ax.plot([0, 1], [0, 1], "k--", lw=2)
    ax.set_xlim([0, 1])
    ax.set_ylim([0, 1.05])
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.set_title("Classifier Comparison (ROC)")
    ax.legend(loc="lower right")
    ax.grid(alpha=0.3)
    plt.tight_layout()
    return plt.gca()


if __name__ == "__main__":
    print("Supervised Learning Toolkit - Demo\n")
    np.random.seed(42)
    X = np.random.randn(100, 2)
    y = X[:, 0] * 2 + X[:, 1] * (-1) + 1 + np.random.randn(100) * 0.5

    lr = LinearRegressionScratch(method="normal")
    lr.fit(X, y)
    print(f"Linear Regression R²: {lr.score(X, y):.4f}")

    from sklearn.datasets import make_classification
    Xc, yc = make_classification(n_samples=100, n_features=2, n_redundant=0, random_state=42)
    logr = LogisticRegressionScratch(epochs=500)
    logr.fit(Xc, yc)
    acc = np.mean(logr.predict(Xc) == yc)
    print(f"Logistic Regression accuracy: {acc:.4f}")
    print("\nDemo complete.")
