"""
Helper Utilities for Supervised Learning Chapter

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
import pandas as pd
from pathlib import Path


def load_housing_data(base_path=None):
    """Load housing dataset. Returns (X, y, df) or (None, None, None) if not found."""
    if base_path is None:
        base_path = Path(__file__).parent.parent / "datasets" / "housing.csv"
    path = Path(base_path)
    if not path.exists():
        return None, None, None
    df = pd.read_csv(path)
    target = "price"
    if target not in df.columns:
        return None, None, df
    X = df.drop(columns=[target])
    y = df[target]
    return X, y, df


def load_credit_data(base_path=None):
    """Load credit dataset. Returns (X, y, df) or (None, None, None) if not found."""
    if base_path is None:
        base_path = Path(__file__).parent.parent / "datasets" / "credit.csv"
    path = Path(base_path)
    if not path.exists():
        return None, None, None
    df = pd.read_csv(path)
    target = "default"
    if target not in df.columns:
        return None, None, df
    X = df.drop(columns=[target])
    y = df[target]
    return X, y, df


def train_test_split(X, y, test_size=0.2, random_state=42):
    """Simple train/test split. X, y as arrays."""
    np.random.seed(random_state)
    n = len(y)
    idx = np.random.permutation(n)
    n_test = int(n * test_size)
    n_train = n - n_test
    train_idx, test_idx = idx[:n_train], idx[n_train:]
    return (X[train_idx], X[test_idx], y[train_idx], y[test_idx])


def add_interaction_terms(X, names=None):
    """Add pairwise interaction terms. X is 2D array."""
    X = np.asarray(X)
    n, p = X.shape
    inter = []
    for i in range(p):
        for j in range(i + 1, p):
            inter.append((X[:, i] * X[:, j]).reshape(-1, 1))
    if inter:
        X_new = np.hstack([X] + inter)
    else:
        X_new = X
    return X_new


def print_classification_report(y_true, y_pred):
    """Print accuracy, precision, recall, F1 for binary classification."""
    tp = np.sum((y_true == 1) & (y_pred == 1))
    tn = np.sum((y_true == 0) & (y_pred == 0))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))
    acc = (tp + tn) / len(y_true)
    prec = tp / (tp + fp) if (tp + fp) > 0 else 0
    rec = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * prec * rec / (prec + rec) if (prec + rec) > 0 else 0
    print(f"Accuracy:  {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall:    {rec:.4f}")
    print(f"F1 Score:  {f1:.4f}")


if __name__ == "__main__":
    print("Utilities - Demo\n")
    X, y, df = load_housing_data()
    if df is not None:
        print(f"Housing data shape: {df.shape}")
    Xc, yc, dfc = load_credit_data()
    if dfc is not None:
        print(f"Credit data shape: {dfc.shape}")
    print("\nDemo complete.")
