"""
Chapter 5 Solutions: Software Design & Best Practices

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

from typing import List, Dict, Any
from abc import ABC, abstractmethod


# Exercise 1: Refactor Spaghetti ML Code
def load_data(data: List[List[float]]) -> tuple:
    """Extract features (X) and targets (y). Assume last column is target."""
    X = [row[:-1] for row in data]
    y = [row[-1] for row in data]
    return X, y


def compute_gradient_simple(X: List[float], y: List[float], w: float, b: float) -> tuple:
    """Compute grad_w and grad_b for MSE (single feature)."""
    n = len(X)
    preds = [w * xi + b for xi in X]
    errors = [p - t for p, t in zip(preds, y)]
    grad_w = (2 / n) * sum(e * x for e, x in zip(errors, X))
    grad_b = (2 / n) * sum(errors)
    return grad_w, grad_b


def train_step_simple(X: List[float], y: List[float], w: float, b: float, lr: float) -> tuple:
    """One gradient descent step. Returns (new_w, new_b)."""
    grad_w, grad_b = compute_gradient_simple(X, y, w, b)
    return w - lr * grad_w, b - lr * grad_b


def evaluate_mse(X: List[float], y: List[float], w: float, b: float) -> float:
    """MSE for y = w*x + b."""
    preds = [w * x + b for x in X]
    n = len(X)
    return sum((p - t) ** 2 for p, t in zip(preds, y)) / n


def refactored_training_pipeline(data: List[List[float]], epochs: int = 500, lr: float = 0.05):
    """Refactored: clean functions, single feature (last col = target)."""
    X_full, y = load_data(data)
    X = [row[0] for row in X_full]  # Single feature
    w, b = 0.0, 0.0
    for _ in range(epochs):
        w, b = train_step_simple(X, y, w, b, lr)
    mse = evaluate_mse(X, y, w, b)
    return w, b, mse


# Exercise 2: Strategy Pattern
class ModelStrategy(ABC):
    @abstractmethod
    def predict(self, X: List[float]) -> List[float]:
        pass


class LinearStrategy(ModelStrategy):
    def __init__(self, w: float = 1.0, b: float = 0.0):
        self.w = w
        self.b = b

    def predict(self, X: List[float]) -> List[float]:
        return [self.w * x + self.b for x in X]


class NullStrategy(ModelStrategy):
    def predict(self, X: List[float]) -> List[float]:
        return [0.0] * len(X)


class Predictor:
    def __init__(self, strategy: ModelStrategy):
        self.strategy = strategy

    def predict(self, X: List[float]) -> List[float]:
        return self.strategy.predict(X)


# Exercise 3: Unit Tests for Preprocessing
def normalize_and_clip(
    data: List[float],
    mean: float,
    std: float,
    low: float = -3.0,
    high: float = 3.0,
) -> List[float]:
    if not data:
        return []
    if std == 0:
        return [0.0] * len(data)
    normalized = [(x - mean) / std for x in data]
    return [max(low, min(high, x)) for x in normalized]


def test_normalize_basic():
    data = [1.0, 2.0, 3.0]
    mean, std = 2.0, 1.0
    result = normalize_and_clip(data, mean, std, -10, 10)
    assert result == [-1.0, 0.0, 1.0]


def test_clip_extreme_values():
    data = [0.0]  # after norm with mean=0, std=1 -> [0]
    result = normalize_and_clip(data, 0, 1, low=-1, high=1)
    assert result == [0.0]
    data_extreme = [-10.0, 10.0]  # normalizing with mean=0, std=1
    result2 = normalize_and_clip(data_extreme, 0, 1, low=-2, high=2)
    assert result2 == [-2.0, 2.0]  # clipped


def test_empty_input():
    assert normalize_and_clip([], 0, 1) == []


# Exercise 4: Config System
class Config:
    def __init__(self, learning_rate: float, epochs: int, model_name: str):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.model_name = model_name

    def validate(self) -> None:
        if self.learning_rate <= 0:
            raise ValueError("learning_rate must be positive")
        if self.epochs < 1:
            raise ValueError("epochs must be >= 1")
        if not self.model_name or not isinstance(self.model_name, str):
            raise ValueError("model_name must be non-empty string")

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Config":
        return cls(
            learning_rate=float(d["learning_rate"]),
            epochs=int(d["epochs"]),
            model_name=str(d["model_name"]),
        )


# Exercise 5: Mini ML Project
class DataLoader:
    def __init__(self, data: List[List[float]], target_idx: int = -1):
        self.X = [row[:target_idx] for row in data]
        self.y = [row[target_idx] for row in data]

    def get_xy(self):
        return self.X, self.y


class SimpleModel:
    def __init__(self):
        self.weights = []
        self.bias = 0.0
        self.in_features = 0

    def fit(self, X: List[List[float]], y: List[float], epochs: int = 100, lr: float = 0.01):
        if not X:
            return
        self.in_features = len(X[0])
        self.weights = [0.0] * self.in_features
        self.bias = 0.0
        n = len(X)
        for _ in range(epochs):
            preds = [sum(w * xi for w, xi in zip(self.weights, row)) + self.bias for row in X]
            errors = [p - t for p, t in zip(preds, y)]
            for j in range(self.in_features):
                grad_j = (2 / n) * sum(e * row[j] for e, row in zip(errors, X))
                self.weights[j] -= lr * grad_j
            self.bias -= lr * (2 / n) * sum(errors)

    def predict(self, X: List[List[float]]) -> List[float]:
        return [
            sum(w * xi for w, xi in zip(self.weights, row)) + self.bias
            for row in X
        ]


class Trainer:
    def __init__(self, config: Dict[str, Any]):
        self.epochs = config.get("epochs", 100)
        self.lr = config.get("learning_rate", 0.01)

    def fit(self, model: SimpleModel, data_loader: DataLoader) -> None:
        X, y = data_loader.get_xy()
        model.fit(X, y, epochs=self.epochs, lr=self.lr)


def run_experiment(config: Dict[str, Any], data: List[List[float]]) -> SimpleModel:
    data_loader = DataLoader(data)
    model = SimpleModel()
    trainer = Trainer(config)
    trainer.fit(model, data_loader)
    return model


# =============================================================================
# __main__ verification
# =============================================================================

if __name__ == "__main__":
    print("Chapter 5 Solutions - Verification\n")

    # Ex 1
    print("Exercise 1: Refactored Training Pipeline")
    data1 = [[1, 2], [2, 4], [3, 6], [4, 8], [5, 10]]
    w, b, mse = refactored_training_pipeline(data1, epochs=500, lr=0.05)
    assert abs(w - 2.0) < 0.1 and abs(b) < 0.1
    print(f"  w={w:.4f}, b={b:.4f}, MSE={mse:.6f}")

    # Ex 2
    print("\nExercise 2: Strategy Pattern")
    pred = Predictor(LinearStrategy(w=2, b=1))
    assert pred.predict([1, 2, 3]) == [3, 5, 7]
    pred_null = Predictor(NullStrategy())
    assert pred_null.predict([1, 2]) == [0, 0]
    print("  LinearStrategy and NullStrategy OK")

    # Ex 3
    print("\nExercise 3: Unit Tests")
    test_normalize_basic()
    test_clip_extreme_values()
    test_empty_input()
    print("  All preprocessing tests passed")

    # Ex 4
    print("\nExercise 4: Config System")
    cfg = Config.from_dict({"learning_rate": 0.001, "epochs": 100, "model_name": "bert"})
    cfg.validate()
    assert cfg.learning_rate == 0.001 and cfg.model_name == "bert"
    print("  Config validated OK")

    # Ex 5
    print("\nExercise 5: Mini ML Project")
    data5 = [[1, 2, 4.1], [2, 3, 7.1], [3, 1, 7.2]]
    model = run_experiment({"epochs": 500, "learning_rate": 0.02}, data5)
    preds = model.predict([[1, 2], [2, 3]])
    print(f"  Trained weights: {[round(x, 3) for x in model.weights]}, b={model.bias:.3f}")
    print(f"  Predictions: {[round(p, 2) for p in preds]}")

    print("\nAll solutions verified!")
