"""
Chapter 1 Exercises: Python Fundamentals for AI

Work through these exercises to solidify your Python skills.
Each exercise builds on concepts from the notebooks.

Try solving them yourself before checking solutions/solutions.py!

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""


# =============================================================================
# Exercise 1: Data Type Detective
# =============================================================================
# Write a function that takes a value and returns a string describing its type
# and properties.
#
# Examples:
#   type_detective(42)        -> "integer, positive, even"
#   type_detective(-3.14)     -> "float, negative"
#   type_detective("hello")   -> "string, length=5, lowercase"
#   type_detective([1,2,3])   -> "list, length=3"
#   type_detective(True)      -> "boolean, True"
#   type_detective(None)      -> "NoneType"

def type_detective(value):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 2: Batch Processor
# =============================================================================
# Write a function that takes a list of numbers and a batch size,
# and returns a list of batch statistics (min, max, mean for each batch).
#
# Example:
#   batch_stats([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], batch_size=3)
#   -> [
#       {"batch": 0, "min": 1, "max": 3, "mean": 2.0},
#       {"batch": 1, "min": 4, "max": 6, "mean": 5.0},
#       {"batch": 2, "min": 7, "max": 9, "mean": 8.0},
#       {"batch": 3, "min": 10, "max": 10, "mean": 10.0},
#   ]

def batch_stats(numbers, batch_size=3):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 3: Text Tokenizer
# =============================================================================
# Write a simple tokenizer that:
# 1. Converts text to lowercase
# 2. Splits into words
# 3. Removes punctuation from word boundaries
# 4. Removes stop words (provided below)
# 5. Returns a list of clean tokens and a vocabulary (set of unique tokens)
#
# STOP_WORDS = {"the", "a", "an", "is", "are", "was", "were", "in", "on", "at",
#               "to", "for", "of", "and", "or", "but", "not", "with", "this",
#               "that", "it", "be", "as", "by", "from", "has", "have", "had"}

STOP_WORDS = {"the", "a", "an", "is", "are", "was", "were", "in", "on", "at",
              "to", "for", "of", "and", "or", "but", "not", "with", "this",
              "that", "it", "be", "as", "by", "from", "has", "have", "had"}

def tokenize(text):
    # YOUR CODE HERE
    # Should return (tokens, vocabulary)
    pass


# =============================================================================
# Exercise 4: Training History Analyzer
# =============================================================================
# Given a training history (dict with "train_loss" and "val_loss" lists),
# write a function that returns:
# - best_epoch: epoch with lowest val_loss (1-indexed)
# - overfit_epoch: first epoch where val_loss starts increasing (or None)
# - final_improvement: percentage improvement from first to best val_loss
# - converged: True if the last 3 val_losses differ by less than threshold
#
# Example:
#   history = {
#       "train_loss": [0.9, 0.5, 0.3, 0.15, 0.08],
#       "val_loss":   [0.95, 0.55, 0.35, 0.32, 0.40],
#   }
#   analyze_training(history) -> {
#       "best_epoch": 4,
#       "overfit_epoch": 5,
#       "final_improvement": 66.3,
#       "converged": False,
#   }

def analyze_training(history, threshold=0.01):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 5: Model Registry
# =============================================================================
# Create a class called ModelRegistry that:
# 1. Stores models with name, version, and metrics
# 2. Can retrieve the best model by any metric
# 3. Can list all versions of a model
# 4. Can compare two models side-by-side
# 5. Has a __str__ method showing the registry summary

class ModelRegistry:
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 6: Data Pipeline Builder
# =============================================================================
# Create a Pipeline class that chains data transformations.
# Each transformation is a function that takes a value and returns a value.
#
# Usage:
#   pipeline = Pipeline()
#   pipeline.add_step("lowercase", str.lower)
#   pipeline.add_step("strip", str.strip)
#   pipeline.add_step("split", str.split)
#   result = pipeline.run("  Hello World  ")
#   # result == ["hello", "world"]
#
#   pipeline.describe()  # Prints: lowercase -> strip -> split

class Pipeline:
    # YOUR CODE HERE
    pass


# =============================================================================
# Test your solutions!
# =============================================================================
if __name__ == "__main__":
    print("Chapter 1 Exercises")
    print("=" * 50)

    # Test Exercise 1
    print("\nExercise 1: Type Detective")
    test_values = [42, -3.14, "hello", [1, 2, 3], True, None]
    for val in test_values:
        result = type_detective(val)
        if result is not None:
            print(f"  {str(val):>15} -> {result}")
        else:
            print(f"  {str(val):>15} -> Not implemented yet")

    # Test Exercise 2
    print("\nExercise 2: Batch Processor")
    result = batch_stats(list(range(1, 11)), batch_size=3)
    if result is not None:
        for batch in result:
            print(f"  Batch {batch['batch']}: min={batch['min']}, max={batch['max']}, mean={batch['mean']}")
    else:
        print("  Not implemented yet")

    # Test Exercise 3
    print("\nExercise 3: Text Tokenizer")
    text = "The quick brown fox jumps over the lazy dog. The dog was not amused."
    result = tokenize(text)
    if result is not None:
        tokens, vocab = result
        print(f"  Tokens: {tokens[:8]}...")
        print(f"  Vocabulary ({len(vocab)} unique): {sorted(vocab)[:8]}...")
    else:
        print("  Not implemented yet")

    # Test Exercise 4
    print("\nExercise 4: Training Analyzer")
    history = {
        "train_loss": [0.9, 0.5, 0.3, 0.15, 0.08],
        "val_loss": [0.95, 0.55, 0.35, 0.32, 0.40],
    }
    result = analyze_training(history)
    if result is not None:
        for k, v in result.items():
            print(f"  {k}: {v}")
    else:
        print("  Not implemented yet")

    # Test Exercise 5
    print("\nExercise 5: Model Registry")
    print("  Not tested automatically — implement and test interactively!")

    # Test Exercise 6
    print("\nExercise 6: Pipeline Builder")
    print("  Not tested automatically — implement and test interactively!")

    print("\n" + "=" * 50)
    print("Complete all exercises, then check solutions/solutions.py!")
