"""
Chapter 3 Solutions: Linear Algebra & Calculus

Generated by Berta AI | Created by Luigi Giacobbe
"""

import math


# Exercise 1: Cosine Similarity
def cosine_similarity(u, v):
    if len(u) != len(v):
        raise ValueError("Vectors must have same dimension")
    dot = sum(a * b for a, b in zip(u, v))
    norm_u = math.sqrt(sum(x * x for x in u))
    norm_v = math.sqrt(sum(x * x for x in v))
    if norm_u == 0 or norm_v == 0:
        return 0.0
    return dot / (norm_u * norm_v)


# Exercise 2: Matrix-Vector Multiplication
def matrix_vector_multiply(A, x):
    if len(A[0]) != len(x):
        raise ValueError("Matrix cols must match vector length")
    return [sum(A[i][j] * x[j] for j in range(len(x))) for i in range(len(A))]


# Exercise 3: Gradient of f(x,y) = x² + 2xy + y²
def gradient_f(x, y):
    # ∂f/∂x = 2x + 2y, ∂f/∂y = 2x + 2y
    return [2 * x + 2 * y, 2 * x + 2 * y]


# Exercise 4: Gradient Descent for Quadratic
def gradient_descent_quadratic(x0, y0, learning_rate=0.1, epochs=100):
    x, y = x0, y0
    for _ in range(epochs):
        gx, gy = 2 * x, 2 * y  # ∇f = (2x, 2y)
        x -= learning_rate * gx
        y -= learning_rate * gy
    loss = x * x + y * y
    return (x, y), loss


# Exercise 5: Linear Regression Class
class LinearRegression:
    def __init__(self, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.w = 0.0
        self.b = 0.0

    def fit(self, X, y):
        X = list(X)
        y = list(y)
        n = len(X)
        if n == 0:
            return self
        w, b = 0.0, 0.0
        for _ in range(self.epochs):
            pred = [w * xi + b for xi in X]
            error = [p - yi for p, yi in zip(pred, y)]
            dw = (2 / n) * sum(e * xi for e, xi in zip(error, X))
            db = (2 / n) * sum(error)
            w -= self.learning_rate * dw
            b -= self.learning_rate * db
        self.w, self.b = w, b
        return self

    def predict(self, X):
        return [self.w * xi + self.b for xi in X]


if __name__ == "__main__":
    print("Chapter 3 Solutions - Verification\n")

    # Ex 1
    print("Exercise 1: Cosine Similarity")
    assert abs(cosine_similarity([1, 0], [1, 0]) - 1.0) < 1e-6
    assert abs(cosine_similarity([1, 0], [-1, 0]) - (-1.0)) < 1e-6
    print(f"  [1,0] vs [1,0]: {cosine_similarity([1, 0], [1, 0]):.4f} (expect 1)")
    print(f"  [1,0] vs [-1,0]: {cosine_similarity([1, 0], [-1, 0]):.4f} (expect -1)")

    # Ex 2
    print("\nExercise 2: Matrix-Vector Multiply")
    A = [[1, 2], [3, 4]]
    x = [5, 6]
    result = matrix_vector_multiply(A, x)
    assert result == [17, 39]
    print(f"  A @ x = {result}")

    # Ex 3
    print("\nExercise 3: Gradient")
    g = gradient_f(1.0, 2.0)
    assert abs(g[0] - 6.0) < 1e-6 and abs(g[1] - 6.0) < 1e-6
    print(f"  ∇f(1,2) = {g} (expect [6, 6])")

    # Ex 4
    print("\nExercise 4: Gradient Descent Quadratic")
    (x_final, y_final), loss = gradient_descent_quadratic(3.0, 4.0, learning_rate=0.1, epochs=50)
    print(f"  Start (3,4), final ({x_final:.6f}, {y_final:.6f}), loss={loss:.8f}")

    # Ex 5
    print("\nExercise 5: Linear Regression")
    X = [1, 2, 3, 4, 5]
    y = [2.1, 3.9, 6.2, 8.1, 9.8]  # approx y = 2x
    model = LinearRegression(learning_rate=0.01, epochs=2000)
    model.fit(X, y)
    pred = model.predict([1.5, 3.5])
    print(f"  Fit: y = {model.w:.3f}x + {model.b:.3f}")
    print(f"  predict([1.5, 3.5]) = {[round(p, 2) for p in pred]}")

    print("\nAll solutions verified!")
