"""
Chapter 8 Exercises: Unsupervised Learning

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np


# =============================================================================
# Exercise 1: Implement K-Means Clustering From Scratch
# =============================================================================
# Build a KMeans class that:
#   - Initializes K centroids randomly from the data points
#   - Assigns each point to the nearest centroid (Euclidean distance)
#   - Recomputes centroids as the mean of assigned points
#   - Repeats for max_iters or until convergence (centroids stop moving)
#
# Methods:
#   - fit(X): Run the K-Means algorithm
#   - predict(X): Assign each row to its nearest centroid
#   - fit_predict(X): fit then predict
#
# Attributes after fit:
#   - centroids: (K, n_features) array
#   - inertia: within-cluster sum of squared distances
#
# Hint: np.linalg.norm(X[:, None] - centroids, axis=2) gives all pairwise distances

class KMeansClustering:
    def __init__(self, n_clusters=3, max_iters=100, random_state=42):
        # YOUR CODE HERE
        pass

    def fit(self, X):
        # YOUR CODE HERE
        pass

    def predict(self, X):
        # YOUR CODE HERE
        pass

    def fit_predict(self, X):
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 2: Implement PCA From Scratch
# =============================================================================
# Build a PCA class that:
#   - Centers the data (subtract mean)
#   - Computes the covariance matrix
#   - Finds eigenvectors/eigenvalues via np.linalg.eigh
#   - Sorts components by descending eigenvalue
#   - Projects data onto the top n_components eigenvectors
#
# Methods:
#   - fit(X): Compute components
#   - transform(X): Project X onto components
#   - fit_transform(X): fit then transform
#
# Attributes after fit:
#   - components_: (n_components, n_features) array
#   - explained_variance_ratio_: fraction of variance per component
#
# Hint: covariance = X_centered.T @ X_centered / (n - 1)

class PCAFromScratch:
    def __init__(self, n_components=2):
        # YOUR CODE HERE
        pass

    def fit(self, X):
        # YOUR CODE HERE
        pass

    def transform(self, X):
        # YOUR CODE HERE
        pass

    def fit_transform(self, X):
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 3: Implement Silhouette Score From Scratch
# =============================================================================
# Compute the silhouette score for a clustering result:
#   For each point i:
#     a(i) = mean distance to all other points in the same cluster
#     b(i) = min over other clusters of mean distance to that cluster's points
#     s(i) = (b(i) - a(i)) / max(a(i), b(i))
#   Return the mean of s(i) over all points.
#
# Parameters:
#   X: (n_samples, n_features) array
#   labels: (n_samples,) array of cluster assignments
#
# Return: float in [-1, 1], higher is better
#
# Hint: Use pairwise Euclidean distances. Handle single-point clusters (s=0).

def silhouette_score_scratch(X, labels):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 4: Anomaly Detection with Z-Score
# =============================================================================
# Implement a simple anomaly detector that:
#   1. Computes the Z-score for each feature: z = (x - mean) / std
#   2. Flags a point as anomalous if any feature has |z| > threshold
#
# Parameters:
#   X: (n_samples, n_features) array
#   threshold: float (default 3.0)
#
# Return: (n_samples,) boolean array, True = anomaly
#
# Hint: np.any(np.abs(z_scores) > threshold, axis=1)

def detect_anomalies_zscore(X, threshold=3.0):
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 5: End-to-End Customer Segmentation Pipeline
# =============================================================================
# Build a pipeline that:
#   1. Loads customer data from datasets/customers.csv
#   2. Scales features with StandardScaler
#   3. Applies PCA (keep 95% variance)
#   4. Uses elbow method to find optimal K (test K=2..8)
#   5. Runs K-Means with optimal K
#   6. Returns segment profiles (mean of original features per cluster)
#
# Return dict: {
#     "n_clusters": int,
#     "labels": array,
#     "profiles": DataFrame (one row per cluster, columns = original features),
#     "inertias": list (for each K tested),
#     "silhouette": float
# }
#
# Hint: The "elbow" can be found by looking for the K where the second
#       derivative of inertia changes most (or just pick K=4 if uncertain).

def customer_segmentation_pipeline(csv_path="datasets/customers.csv"):
    # YOUR CODE HERE
    pass
