#!/usr/bin/env python3
"""
Interactive Data Explorer

A command-line tool for exploring CSV datasets. Demonstrates Python fundamentals
in a practical, real-world script that you can adapt for your own projects.

Usage:
    python scripts/data_explorer.py                    # Use sample dataset
    python scripts/data_explorer.py path/to/data.csv   # Use your own data

Generated by Berta AI | Created by Luigi Giacobbe
"""

import csv
import os
import sys
from collections import Counter
from pathlib import Path


def load_csv(filepath):
    """Load a CSV file and return headers + rows."""
    with open(filepath, "r") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    if not rows:
        return [], []
    return list(rows[0].keys()), rows


def infer_type(value):
    """Infer the type of a string value."""
    try:
        int(value)
        return "integer"
    except ValueError:
        pass
    try:
        float(value)
        return "float"
    except ValueError:
        pass
    return "string"


def compute_column_stats(rows, column):
    """Compute statistics for a column."""
    values = [row[column] for row in rows if row[column]]
    col_type = infer_type(values[0]) if values else "unknown"

    stats = {
        "name": column,
        "type": col_type,
        "count": len(values),
        "missing": len(rows) - len(values),
        "unique": len(set(values)),
    }

    if col_type in ("integer", "float"):
        numeric = [float(v) for v in values]
        stats.update({
            "min": min(numeric),
            "max": max(numeric),
            "mean": sum(numeric) / len(numeric),
            "median": sorted(numeric)[len(numeric) // 2],
        })
    else:
        freq = Counter(values).most_common(5)
        stats["top_values"] = freq

    return stats


def print_summary(headers, rows):
    """Print a summary of the dataset."""
    print(f"\nDataset Summary")
    print(f"{'=' * 50}")
    print(f"Rows:    {len(rows)}")
    print(f"Columns: {len(headers)}")
    print()

    for header in headers:
        stats = compute_column_stats(rows, header)
        print(f"  {stats['name']}")
        print(f"    Type: {stats['type']} | Unique: {stats['unique']} | Missing: {stats['missing']}")
        if "mean" in stats:
            print(f"    Range: [{stats['min']:.4f}, {stats['max']:.4f}]")
            print(f"    Mean: {stats['mean']:.4f} | Median: {stats['median']:.4f}")
        elif "top_values" in stats:
            top = ", ".join(f"{v}({c})" for v, c in stats["top_values"][:3])
            print(f"    Top values: {top}")
        print()


def print_head(rows, n=5):
    """Print the first n rows."""
    if not rows:
        print("No data.")
        return
    headers = list(rows[0].keys())
    widths = {h: max(len(h), max(len(str(r.get(h, ""))) for r in rows[:n])) for h in headers}

    header_line = " | ".join(h.ljust(widths[h]) for h in headers)
    print(f"\n{header_line}")
    print("-" * len(header_line))
    for row in rows[:n]:
        line = " | ".join(str(row.get(h, "")).ljust(widths[h]) for h in headers)
        print(line)


def interactive_mode(headers, rows):
    """Run the interactive exploration loop."""
    commands = {
        "summary": "Show dataset summary",
        "head": "Show first 5 rows",
        "columns": "List all columns",
        "stats <col>": "Show stats for a column",
        "filter <col> <val>": "Filter rows where col == val",
        "count <col>": "Count values in a column",
        "quit": "Exit",
    }

    print("\nInteractive Data Explorer")
    print("=" * 40)
    print(f"Loaded {len(rows)} rows, {len(headers)} columns\n")
    print("Commands:")
    for cmd, desc in commands.items():
        print(f"  {cmd:>20} - {desc}")

    while True:
        try:
            user_input = input("\n> ").strip()
        except (EOFError, KeyboardInterrupt):
            break

        if not user_input:
            continue

        parts = user_input.split()
        cmd = parts[0].lower()

        if cmd == "quit":
            print("Goodbye!")
            break
        elif cmd == "summary":
            print_summary(headers, rows)
        elif cmd == "head":
            n = int(parts[1]) if len(parts) > 1 else 5
            print_head(rows, n)
        elif cmd == "columns":
            for i, h in enumerate(headers, 1):
                print(f"  {i}. {h}")
        elif cmd == "stats" and len(parts) > 1:
            col = parts[1]
            if col in headers:
                stats = compute_column_stats(rows, col)
                for k, v in stats.items():
                    print(f"  {k}: {v}")
            else:
                print(f"  Column '{col}' not found. Use 'columns' to see available columns.")
        elif cmd == "filter" and len(parts) > 2:
            col, val = parts[1], " ".join(parts[2:])
            if col in headers:
                filtered = [r for r in rows if r.get(col) == val]
                print(f"  {len(filtered)} rows where {col} == '{val}'")
                print_head(filtered, 5)
            else:
                print(f"  Column '{col}' not found.")
        elif cmd == "count" and len(parts) > 1:
            col = parts[1]
            if col in headers:
                counts = Counter(r.get(col) for r in rows)
                for val, cnt in counts.most_common(10):
                    bar = "#" * min(cnt, 40)
                    print(f"  {str(val):>20}: {cnt:>5} {bar}")
            else:
                print(f"  Column '{col}' not found.")
        else:
            print(f"  Unknown command: '{user_input}'. Type a command from the list above.")


def main():
    if len(sys.argv) > 1:
        filepath = sys.argv[1]
    else:
        filepath = str(Path(__file__).parent.parent / "datasets" / "sample_data.csv")

    if not os.path.exists(filepath):
        print(f"File not found: {filepath}")
        print("Run notebook 03_advanced.ipynb first to generate sample_data.csv,")
        print("or provide your own CSV file as an argument.")
        sys.exit(1)

    headers, rows = load_csv(filepath)
    interactive_mode(headers, rows)


if __name__ == "__main__":
    main()
