"""
Utility Functions for AI Projects

A collection of reusable helper functions demonstrating Python best practices.
Import and use these in your own projects.

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import math
import random
import time
import functools
from collections import Counter
from datetime import datetime


def timer(func):
    """Decorator that measures and prints execution time."""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start = time.perf_counter()
        result = func(*args, **kwargs)
        elapsed = time.perf_counter() - start
        print(f"[{func.__name__}] {elapsed:.4f}s")
        return result
    return wrapper


def normalize(values, method="min-max"):
    """Normalize a list of numbers.

    Args:
        values: List of numeric values.
        method: 'min-max' (0-1 range) or 'z-score' (mean=0, std=1).

    Returns:
        List of normalized values.
    """
    if not values:
        return []

    if method == "min-max":
        lo, hi = min(values), max(values)
        if hi == lo:
            return [0.5] * len(values)
        return [(v - lo) / (hi - lo) for v in values]
    elif method == "z-score":
        mean = sum(values) / len(values)
        std = math.sqrt(sum((v - mean) ** 2 for v in values) / len(values))
        if std == 0:
            return [0.0] * len(values)
        return [(v - mean) / std for v in values]
    else:
        raise ValueError(f"Unknown method: {method}")


def train_test_split(data, test_ratio=0.2, seed=None):
    """Split data into training and test sets.

    Args:
        data: List of items.
        test_ratio: Fraction of data for testing (0-1).
        seed: Random seed for reproducibility.

    Returns:
        Tuple of (train_data, test_data).
    """
    if seed is not None:
        random.seed(seed)
    shuffled = data.copy()
    random.shuffle(shuffled)
    split_idx = int(len(shuffled) * (1 - test_ratio))
    return shuffled[:split_idx], shuffled[split_idx:]


def accuracy_score(y_true, y_pred):
    """Calculate accuracy: fraction of correct predictions."""
    if len(y_true) != len(y_pred):
        raise ValueError("Lists must have the same length")
    correct = sum(1 for t, p in zip(y_true, y_pred) if t == p)
    return correct / len(y_true) if y_true else 0.0


def confusion_matrix(y_true, y_pred, labels=None):
    """Build a confusion matrix as a dictionary of dictionaries.

    Returns:
        Dict[actual_label -> Dict[predicted_label -> count]]
    """
    if labels is None:
        labels = sorted(set(y_true) | set(y_pred))
    matrix = {actual: {pred: 0 for pred in labels} for actual in labels}
    for t, p in zip(y_true, y_pred):
        matrix[t][p] += 1
    return matrix


def batch_iterator(data, batch_size=32, shuffle=True, seed=None):
    """Yield batches from data, similar to PyTorch DataLoader.

    Args:
        data: List of items.
        batch_size: Number of items per batch.
        shuffle: Whether to shuffle before batching.
        seed: Random seed for reproducibility.

    Yields:
        Lists of items, each of length <= batch_size.
    """
    if seed is not None:
        random.seed(seed)
    indices = list(range(len(data)))
    if shuffle:
        random.shuffle(indices)
    for start in range(0, len(indices), batch_size):
        batch_indices = indices[start:start + batch_size]
        yield [data[i] for i in batch_indices]


def word_frequencies(text, top_n=10):
    """Count word frequencies in a text string.

    Args:
        text: Input text string.
        top_n: Number of top words to return.

    Returns:
        List of (word, count) tuples.
    """
    words = text.lower().split()
    clean = [w.strip(".,!?;:'\"()[]{}") for w in words]
    clean = [w for w in clean if w]
    return Counter(clean).most_common(top_n)


def cosine_similarity(vec_a, vec_b):
    """Calculate cosine similarity between two vectors.

    Args:
        vec_a: First vector (list of floats).
        vec_b: Second vector (list of floats).

    Returns:
        Cosine similarity (-1 to 1).
    """
    if len(vec_a) != len(vec_b):
        raise ValueError("Vectors must have the same dimension")
    dot = sum(a * b for a, b in zip(vec_a, vec_b))
    mag_a = math.sqrt(sum(a ** 2 for a in vec_a))
    mag_b = math.sqrt(sum(b ** 2 for b in vec_b))
    if mag_a == 0 or mag_b == 0:
        return 0.0
    return dot / (mag_a * mag_b)


def format_metrics(metrics, precision=4):
    """Format a metrics dictionary for display.

    Args:
        metrics: Dict of metric_name -> value.
        precision: Number of decimal places.

    Returns:
        Formatted string.
    """
    lines = []
    max_key_len = max(len(k) for k in metrics) if metrics else 0
    for key, value in metrics.items():
        if isinstance(value, float):
            lines.append(f"  {key:>{max_key_len}}: {value:.{precision}f}")
        else:
            lines.append(f"  {key:>{max_key_len}}: {value}")
    return "\n".join(lines)


if __name__ == "__main__":
    print("Berta Utilities - Demo\n")

    data = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
    print(f"Original: {data}")
    print(f"Min-Max:  {[round(v, 2) for v in normalize(data, 'min-max')]}")
    print(f"Z-Score:  {[round(v, 2) for v in normalize(data, 'z-score')]}")

    print(f"\nCosine similarity:")
    a = [1, 0, 1]
    b = [0, 1, 0]
    c = [1, 0, 1]
    print(f"  [1,0,1] vs [0,1,0] = {cosine_similarity(a, b):.4f}")
    print(f"  [1,0,1] vs [1,0,1] = {cosine_similarity(a, c):.4f}")

    metrics = {"accuracy": 0.923, "f1_score": 0.917, "loss": 0.184}
    print(f"\nFormatted metrics:\n{format_metrics(metrics)}")
