#!/usr/bin/env python3
"""
Linear Algebra Toolkit

Vector and matrix operations, plus gradient descent for linear regression.
Used throughout the Berta AI curriculum.

Usage:
    python scripts/linear_algebra_toolkit.py

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import math


# -----------------------------------------------------------------------------
# Vector operations
# -----------------------------------------------------------------------------

def vector_add(u, v):
    """Add two vectors element-wise."""
    if len(u) != len(v):
        raise ValueError("Vectors must have same dimension")
    return [a + b for a, b in zip(u, v)]


def vector_subtract(u, v):
    """Subtract vectors: u - v."""
    if len(u) != len(v):
        raise ValueError("Vectors must have same dimension")
    return [a - b for a, b in zip(u, v)]


def vector_scale(c, u):
    """Multiply vector by scalar."""
    return [c * x for x in u]


def vector_dot(u, v):
    """Dot product: sum of element-wise products."""
    if len(u) != len(v):
        raise ValueError("Vectors must have same dimension")
    return sum(a * b for a, b in zip(u, v))


def vector_norm(u, p=2):
    """Compute Lp norm. p=1 for L1, p=2 for L2 (default)."""
    if p == 1:
        return sum(abs(x) for x in u)
    if p == 2:
        return math.sqrt(sum(x * x for x in u))
    return (sum(abs(x) ** p for x in u)) ** (1 / p)


def cosine_similarity(u, v):
    """Cosine similarity: dot product normalized by L2 norms."""
    dot = vector_dot(u, v)
    norm_u = vector_norm(u, 2)
    norm_v = vector_norm(v, 2)
    if norm_u == 0 or norm_v == 0:
        return 0.0
    return dot / (norm_u * norm_v)


# -----------------------------------------------------------------------------
# Matrix operations
# -----------------------------------------------------------------------------

def matrix_transpose(A):
    """Transpose: rows become columns."""
    if not A:
        return []
    n_rows, n_cols = len(A), len(A[0])
    return [[A[i][j] for i in range(n_rows)] for j in range(n_cols)]


def matrix_multiply(A, B):
    """Matrix multiply: A (m×k) @ B (k×n) -> (m×n)."""
    m, k1 = len(A), len(A[0])
    k2, n = len(B), len(B[0])
    if k1 != k2:
        raise ValueError(f"Inner dims must match: {k1} vs {k2}")
    result = [[0] * n for _ in range(m)]
    for i in range(m):
        for j in range(n):
            result[i][j] = sum(A[i][kk] * B[kk][j] for kk in range(k1))
    return result


def matrix_vector_multiply(A, x):
    """Matrix (m×n) times vector (n) -> vector (m)."""
    return [sum(A[i][j] * x[j] for j in range(len(x))) for i in range(len(A))]


# -----------------------------------------------------------------------------
# Gradient descent for linear regression
# -----------------------------------------------------------------------------

def gradient_descent(X, y, learning_rate=0.01, epochs=1000):
    """Gradient descent for linear regression y ≈ Xw + b.

    Args:
        X: List of lists (samples x features) or flat list (single feature).
        y: Target values.
        learning_rate: Step size.
        epochs: Number of iterations.

    Returns:
        Tuple of (w, b, history) where history is list of MSE per epoch.
    """
    try:
        import numpy as np
    except ImportError:
        raise ImportError("NumPy required for gradient_descent")

    X = np.array(X)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    y = np.array(y).reshape(-1, 1)
    n, d = X.shape

    w = np.zeros((d, 1))
    b = 0.0
    history = []

    for _ in range(epochs):
        pred = X @ w + b
        error = pred - y
        dw = (2 / n) * (X.T @ error)
        db = (2 / n) * np.sum(error)
        w -= learning_rate * dw
        b -= learning_rate * db
        mse = float(np.mean(error ** 2))
        history.append(mse)

    return w.flatten().tolist(), float(b), history


if __name__ == "__main__":
    print("Linear Algebra Toolkit - Demo\n")

    # Vector ops
    u, v = [1, 2, 3], [4, 5, 6]
    print("Vector operations:")
    print(f"  u + v = {vector_add(u, v)}")
    print(f"  u · v = {vector_dot(u, v)}")
    print(f"  ||u||₂ = {vector_norm(u):.4f}")
    print(f"  cosine(u, v) = {cosine_similarity(u, v):.4f}")

    # Matrix ops
    A = [[1, 2], [3, 4]]
    B = [[5, 6], [7, 8]]
    print("\nMatrix operations:")
    print(f"  A @ B = {matrix_multiply(A, B)}")
    print(f"  A^T = {matrix_transpose(A)}")

    # Gradient descent
    print("\nGradient descent (linear regression):")
    import numpy as np
    np.random.seed(42)
    X = np.linspace(0, 10, 30).tolist()
    y = (2 * np.array(X) + 1 + np.random.randn(30) * 0.5).tolist()
    w, b, hist = gradient_descent(X, y, learning_rate=0.01, epochs=500)
    print(f"  Learned: y = {w[0]:.3f}x + {b:.3f}")
    print(f"  Final MSE: {hist[-1]:.6f}")
