"""
Reusable Math Utilities for Linear Algebra & Calculus

Helper functions for the Berta AI linear algebra curriculum.

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import math


def euclidean_distance(u, v):
    """L2 distance between two vectors. Used in k-NN, k-means."""
    if len(u) != len(v):
        raise ValueError("Vectors must have same dimension")
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(u, v)))


def numerical_derivative(f, x, h=1e-5):
    """Approximate f'(x) using central finite differences."""
    return (f(x + h) - f(x - h)) / (2 * h)


def numerical_gradient(f, point, h=1e-5):
    """Compute gradient at point using finite differences.
    f should accept *point (e.g., f(x, y) for point=[x, y]).
    """
    grad = []
    for i in range(len(point)):
        point_plus = point[:i] + [point[i] + h] + point[i + 1:]
        point_minus = point[:i] + [point[i] - h] + point[i + 1:]
        g = (f(*point_plus) - f(*point_minus)) / (2 * h)
        grad.append(g)
    return grad


def identity_matrix(n):
    """Create n×n identity matrix."""
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]


def rotation_matrix_2d(angle_degrees):
    """2D rotation matrix (counterclockwise). Used in data augmentation."""
    theta = math.radians(angle_degrees)
    c, s = math.cos(theta), math.sin(theta)
    return [[c, -s], [s, c]]


def mse(predictions, targets):
    """Mean squared error between two sequences."""
    if len(predictions) != len(targets):
        raise ValueError("Sequences must have same length")
    n = len(predictions)
    return sum((p - t) ** 2 for p, t in zip(predictions, targets)) / n


def normalize_vector(u, norm_type="l2"):
    """Normalize vector to unit length. norm_type: 'l1' or 'l2'."""
    if norm_type == "l1":
        s = sum(abs(x) for x in u)
        if s == 0:
            return [0.0] * len(u)
        return [x / s for x in u]
    elif norm_type == "l2":
        s = math.sqrt(sum(x * x for x in u))
        if s == 0:
            return [0.0] * len(u)
        return [x / s for x in u]
    else:
        raise ValueError(f"Unknown norm_type: {norm_type}")


if __name__ == "__main__":
    print("Math Utilities - Demo\n")

    # Euclidean distance
    print("Euclidean distance:", euclidean_distance([0, 0], [3, 4]))

    # Numerical derivative: f(x)=x^2 => f'(2)=4
    print("f'(2) for f(x)=x²:", numerical_derivative(lambda x: x**2, 2))

    # Numerical gradient
    def f_xy(x, y):
        return x**2 + y**2
    print("∇f(1,1) for f=x²+y²:", numerical_gradient(f_xy, [1.0, 1.0]))

    # MSE
    print("MSE([1,2,3], [1.1,1.9,3.2]):", mse([1, 2, 3], [1.1, 1.9, 3.2]))
