#!/usr/bin/env python3
"""
Berta Chapter Template Generator

Creates the scaffolding for a new Berta chapter with the standard structure:
- README.md with learning objectives
- 3 Jupyter notebooks (intro, intermediate, advanced)
- Scripts directory with main application and utilities
- Exercises with solutions directory
- Assets and datasets directories
- requirements.txt

Usage:
    python templates/chapter_template.py --number 2 --title "Data Structures & Algorithms"
    python templates/chapter_template.py -n 2 -t "Data Structures & Algorithms" --hours 6

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import argparse
import json
import os
import sys
from pathlib import Path
from datetime import datetime


NOTEBOOK_TEMPLATE = {
    "cells": [],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}


def markdown_cell(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source.split("\n")}


def code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.split("\n"),
    }


def create_chapter(number, title, hours=8, track="Foundation", prereqs=None):
    slug = title.lower().replace(" ", "-").replace("&", "and")
    for char in ".,!?;:'\"()[]{}":
        slug = slug.replace(char, "")
    chapter_dir = Path("chapters") / f"chapter-{number:02d}-{slug}"

    dirs = [
        chapter_dir / "notebooks",
        chapter_dir / "scripts",
        chapter_dir / "exercises" / "solutions",
        chapter_dir / "assets" / "diagrams",
        chapter_dir / "datasets",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    prereq_str = ", ".join(str(p) for p in (prereqs or [])) or "None"
    readme_content = f"""# Chapter {number}: {title}

**Track**: {track} | **Time**: {hours} hours | **Prerequisites**: {prereq_str}

---

## Learning Objectives

By the end of this chapter, you will be able to:

- [ ] Objective 1 (replace with actual objectives)
- [ ] Objective 2
- [ ] Objective 3

---

## Chapter Structure

```
chapter-{number:02d}-{slug}/
├── README.md
├── notebooks/
│   ├── 01_introduction.ipynb
│   ├── 02_intermediate.ipynb
│   └── 03_advanced.ipynb
├── scripts/
│   ├── main_application.py
│   └── utilities.py
├── exercises/
│   ├── exercises.py
│   └── solutions/
│       └── solutions.py
├── assets/
│   └── diagrams/
├── datasets/
└── requirements.txt
```

## How to Use

1. Read this README
2. Work through notebooks in order (01 -> 02 -> 03)
3. Try the exercises before checking solutions
4. Explore scripts for production patterns

---

**Generated by Berta AI | Created by Luigi Pascal Rondanini**

*Created: {datetime.now().strftime('%B %Y')}*
"""
    (chapter_dir / "README.md").write_text(readme_content)

    notebooks = [
        ("01_introduction", "Introduction", f"Welcome to Chapter {number}! Start here."),
        ("02_intermediate", "Intermediate", "Building on the basics with more complex patterns."),
        ("03_advanced", "Advanced", "Advanced techniques and a capstone project."),
    ]

    for filename, level, description in notebooks:
        nb = dict(NOTEBOOK_TEMPLATE)
        nb["cells"] = [
            markdown_cell(
                f"# Chapter {number}: {title}\n"
                f"## Notebook - {level}\n\n"
                f"{description}\n\n"
                f"**Time estimate:** {hours // 3} hours\n\n"
                f"---\n"
                f"*Generated by Berta AI | Created by Luigi Pascal Rondanini*"
            ),
            markdown_cell("## 1. Getting Started\n\nAdd your content here."),
            code_cell("# Your code here\nprint('Hello from Berta Chapters!')"),
        ]
        nb_path = chapter_dir / "notebooks" / f"{filename}.ipynb"
        nb_path.write_text(json.dumps(nb, indent=1))

    main_app = f'''"""
Main Application - Chapter {number}: {title}

Production-ready implementation demonstrating key concepts.

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""


def main():
    print("Chapter {number}: {title}")
    print("Replace this with your main application logic.")


if __name__ == "__main__":
    main()
'''
    (chapter_dir / "scripts" / "main_application.py").write_text(main_app)

    utils = f'''"""
Utility Functions - Chapter {number}: {title}

Reusable helper functions for this chapter.

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""


def placeholder():
    """Replace with actual utility functions."""
    pass
'''
    (chapter_dir / "scripts" / "utilities.py").write_text(utils)

    exercises = f'''"""
Chapter {number} Exercises: {title}

Practice problems to solidify your understanding.
Try solving them before checking solutions/solutions.py!

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""


# Exercise 1: [Name]
# Description: ...
def exercise_1():
    # YOUR CODE HERE
    pass


# Exercise 2: [Name]
# Description: ...
def exercise_2():
    # YOUR CODE HERE
    pass


if __name__ == "__main__":
    print("Chapter {number} Exercises")
    print("=" * 40)
    print("Implement the functions above and run this file to test!")
'''
    (chapter_dir / "exercises" / "exercises.py").write_text(exercises)

    solutions = f'''"""
Chapter {number} Solutions: {title}

Solutions to all exercises. Try solving them yourself first!

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""


def exercise_1():
    # Solution here
    pass


def exercise_2():
    # Solution here
    pass
'''
    (chapter_dir / "exercises" / "solutions" / "solutions.py").write_text(solutions)

    (chapter_dir / "requirements.txt").write_text("jupyter>=1.0.0\nnotebook>=7.0.0\n")

    print(f"Chapter {number} created at: {chapter_dir}")
    print(f"  Title: {title}")
    print(f"  Track: {track}")
    print(f"  Hours: {hours}")
    print(f"  Prerequisites: {prereq_str}")
    print(f"\nFiles created:")
    for path in sorted(chapter_dir.rglob("*")):
        if path.is_file():
            rel = path.relative_to(chapter_dir)
            print(f"  {rel}")

    return chapter_dir


def main():
    parser = argparse.ArgumentParser(description="Generate a new Berta chapter")
    parser.add_argument("-n", "--number", type=int, required=True, help="Chapter number")
    parser.add_argument("-t", "--title", type=str, required=True, help="Chapter title")
    parser.add_argument("--hours", type=int, default=8, help="Estimated hours (default: 8)")
    parser.add_argument("--track", type=str, default="Foundation",
                        choices=["Foundation", "Practitioner", "Advanced"],
                        help="Curriculum track")
    parser.add_argument("--prereqs", type=int, nargs="*", help="Prerequisite chapter numbers")

    args = parser.parse_args()
    os.chdir(Path(__file__).parent.parent)
    create_chapter(args.number, args.title, args.hours, args.track, args.prereqs)


if __name__ == "__main__":
    main()
