#!/usr/bin/env python3
"""
Algorithm Visualizer

Interactive CLI tool to visualize sorting and searching algorithms step-by-step.

Usage:
    python scripts/algorithm_visualizer.py

Generated by Berta AI | Created by Luigi Giacobbe
"""

import random
import time
import sys


def visualize_sort(arr, name="Sort"):
    """Print array with bars for visual comparison."""
    max_val = max(arr) if arr else 1
    print(f"\n{name}: {arr}")
    for val in arr:
        bar = "#" * int(val / max_val * 40)
        print(f"  {val:>4} |{bar}")


def bubble_sort_visual(arr):
    """Bubble sort with step-by-step visualization."""
    data = arr.copy()
    n = len(data)
    steps = 0

    print("=== Bubble Sort ===")
    print(f"Start: {data}")

    for i in range(n):
        swapped = False
        for j in range(0, n - i - 1):
            steps += 1
            if data[j] > data[j + 1]:
                data[j], data[j + 1] = data[j + 1], data[j]
                swapped = True
        if not swapped:
            break
        print(f"Pass {i + 1}: {data}")

    print(f"Done in {steps} comparisons")
    return data


def selection_sort_visual(arr):
    """Selection sort with step-by-step visualization."""
    data = arr.copy()
    n = len(data)

    print("\n=== Selection Sort ===")
    print(f"Start: {data}")

    for i in range(n):
        min_idx = i
        for j in range(i + 1, n):
            if data[j] < data[min_idx]:
                min_idx = j
        data[i], data[min_idx] = data[min_idx], data[i]
        print(f"Step {i + 1}: {data} (placed {data[i]} at index {i})")

    return data


def binary_search_visual(arr, target):
    """Binary search with step-by-step visualization."""
    print(f"\n=== Binary Search for {target} ===")
    print(f"Array: {arr}")

    left, right = 0, len(arr) - 1
    step = 0

    while left <= right:
        step += 1
        mid = (left + right) // 2
        mid_val = arr[mid]

        region = [" "] * len(arr)
        for i in range(left, right + 1):
            region[i] = "-"
        region[mid] = "^"
        region_str = "".join(f"{r:>4}" for r in region)

        print(f"  Step {step}: check index {mid} (value={mid_val})")
        print(f"         {region_str}")

        if mid_val == target:
            print(f"  Found at index {mid}!")
            return mid
        elif mid_val < target:
            left = mid + 1
            print(f"         {target} > {mid_val}, search right half")
        else:
            right = mid - 1
            print(f"         {target} < {mid_val}, search left half")

    print(f"  Not found after {step} steps")
    return -1


def main():
    print("Algorithm Visualizer")
    print("=" * 40)

    random.seed(42)
    data = [random.randint(1, 50) for _ in range(10)]

    bubble_sort_visual(data.copy())
    selection_sort_visual(data.copy())

    sorted_data = sorted(data)
    binary_search_visual(sorted_data, sorted_data[7])
    binary_search_visual(sorted_data, 99)


if __name__ == "__main__":
    main()
