"""
Data Structure Utilities

Reusable implementations of common data structures and algorithms.

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

from collections import defaultdict, deque
import math


class MinHeap:
    """A min-heap for priority queue operations."""

    def __init__(self):
        self._data = []

    def push(self, item):
        self._data.append(item)
        self._sift_up(len(self._data) - 1)

    def pop(self):
        if not self._data:
            raise IndexError("Pop from empty heap")
        if len(self._data) == 1:
            return self._data.pop()
        root = self._data[0]
        self._data[0] = self._data.pop()
        self._sift_down(0)
        return root

    def peek(self):
        if not self._data:
            raise IndexError("Peek at empty heap")
        return self._data[0]

    def _sift_up(self, idx):
        while idx > 0:
            parent = (idx - 1) // 2
            if self._data[idx] < self._data[parent]:
                self._data[idx], self._data[parent] = self._data[parent], self._data[idx]
                idx = parent
            else:
                break

    def _sift_down(self, idx):
        n = len(self._data)
        while True:
            smallest = idx
            left = 2 * idx + 1
            right = 2 * idx + 2
            if left < n and self._data[left] < self._data[smallest]:
                smallest = left
            if right < n and self._data[right] < self._data[smallest]:
                smallest = right
            if smallest != idx:
                self._data[idx], self._data[smallest] = self._data[smallest], self._data[idx]
                idx = smallest
            else:
                break

    def __len__(self):
        return len(self._data)


class Trie:
    """A trie (prefix tree) for efficient string operations."""

    def __init__(self):
        self.children = {}
        self.is_end = False
        self.count = 0

    def insert(self, word):
        node = self
        for char in word:
            if char not in node.children:
                node.children[char] = Trie()
            node = node.children[char]
        node.is_end = True
        node.count += 1

    def search(self, word):
        node = self._find_node(word)
        return node is not None and node.is_end

    def starts_with(self, prefix):
        return self._find_node(prefix) is not None

    def autocomplete(self, prefix, limit=10):
        node = self._find_node(prefix)
        if node is None:
            return []
        results = []
        self._collect(node, prefix, results, limit)
        return results

    def _find_node(self, prefix):
        node = self
        for char in prefix:
            if char not in node.children:
                return None
            node = node.children[char]
        return node

    def _collect(self, node, prefix, results, limit):
        if len(results) >= limit:
            return
        if node.is_end:
            results.append(prefix)
        for char in sorted(node.children):
            self._collect(node.children[char], prefix + char, results, limit)


def topological_sort(graph):
    """Topological sort of a DAG (used in pipeline scheduling).

    Args:
        graph: Dict mapping node -> list of dependencies.

    Returns:
        List of nodes in execution order, or None if cycle exists.
    """
    in_degree = defaultdict(int)
    for node in graph:
        in_degree.setdefault(node, 0)
        for dep in graph[node]:
            in_degree[dep] += 1

    queue = deque(node for node in in_degree if in_degree[node] == 0)
    result = []

    while queue:
        node = queue.popleft()
        result.append(node)
        for dep in graph.get(node, []):
            in_degree[dep] -= 1
            if in_degree[dep] == 0:
                queue.append(dep)

    return result if len(result) == len(in_degree) else None


if __name__ == "__main__":
    print("Data Structure Utilities - Demo\n")

    # Trie demo
    trie = Trie()
    words = ["tensor", "tensorflow", "torch", "training", "transformer",
             "transfer", "test", "tokenizer", "token"]
    for w in words:
        trie.insert(w)

    print("Trie autocomplete:")
    for prefix in ["t", "tr", "ten", "tok"]:
        matches = trie.autocomplete(prefix, limit=5)
        print(f"  '{prefix}' -> {matches}")

    # Heap demo
    heap = MinHeap()
    for val in [5, 3, 8, 1, 9, 2]:
        heap.push(val)

    print("\nMin-heap extraction order:")
    while len(heap) > 0:
        print(f"  {heap.pop()}", end="")
    print()

    # Topological sort demo
    pipeline = {
        "raw_data": ["clean"],
        "clean": ["features", "labels"],
        "features": ["train"],
        "labels": ["train"],
        "train": ["evaluate"],
        "evaluate": ["deploy"],
    }
    order = topological_sort(pipeline)
    print(f"\nPipeline execution order: {order}")
