"""
Chapter 1 Solutions: Python Fundamentals for AI

Solutions to all exercises. Try solving them yourself first!

Generated by Berta AI | Created by Luigi Giacobbe
"""

STOP_WORDS = {"the", "a", "an", "is", "are", "was", "were", "in", "on", "at",
              "to", "for", "of", "and", "or", "but", "not", "with", "this",
              "that", "it", "be", "as", "by", "from", "has", "have", "had"}


# =============================================================================
# Exercise 1: Data Type Detective
# =============================================================================
def type_detective(value):
    if value is None:
        return "NoneType"
    if isinstance(value, bool):
        return f"boolean, {value}"
    if isinstance(value, int):
        sign = "positive" if value > 0 else "negative" if value < 0 else "zero"
        parity = "even" if value % 2 == 0 else "odd"
        return f"integer, {sign}, {parity}"
    if isinstance(value, float):
        sign = "positive" if value > 0 else "negative" if value < 0 else "zero"
        return f"float, {sign}"
    if isinstance(value, str):
        case = "lowercase" if value.islower() else "uppercase" if value.isupper() else "mixed"
        return f"string, length={len(value)}, {case}"
    if isinstance(value, list):
        return f"list, length={len(value)}"
    if isinstance(value, dict):
        return f"dict, keys={len(value)}"
    if isinstance(value, tuple):
        return f"tuple, length={len(value)}"
    if isinstance(value, set):
        return f"set, size={len(value)}"
    return f"{type(value).__name__}"


# =============================================================================
# Exercise 2: Batch Processor
# =============================================================================
def batch_stats(numbers, batch_size=3):
    results = []
    for i in range(0, len(numbers), batch_size):
        batch = numbers[i:i + batch_size]
        results.append({
            "batch": i // batch_size,
            "min": min(batch),
            "max": max(batch),
            "mean": sum(batch) / len(batch),
        })
    return results


# =============================================================================
# Exercise 3: Text Tokenizer
# =============================================================================
def tokenize(text):
    words = text.lower().split()
    tokens = []
    for word in words:
        clean = word.strip(".,!?;:'\"()[]{}—-")
        if clean and clean not in STOP_WORDS:
            tokens.append(clean)
    vocabulary = set(tokens)
    return tokens, vocabulary


# =============================================================================
# Exercise 4: Training History Analyzer
# =============================================================================
def analyze_training(history, threshold=0.01):
    val_losses = history["val_loss"]

    best_idx = val_losses.index(min(val_losses))
    best_epoch = best_idx + 1

    overfit_epoch = None
    for i in range(1, len(val_losses)):
        if val_losses[i] > val_losses[i - 1]:
            overfit_epoch = i + 1
            break

    first_loss = val_losses[0]
    best_loss = val_losses[best_idx]
    improvement = ((first_loss - best_loss) / first_loss) * 100

    converged = False
    if len(val_losses) >= 3:
        last_3 = val_losses[-3:]
        max_diff = max(last_3) - min(last_3)
        converged = max_diff < threshold

    return {
        "best_epoch": best_epoch,
        "overfit_epoch": overfit_epoch,
        "final_improvement": round(improvement, 1),
        "converged": converged,
    }


# =============================================================================
# Exercise 5: Model Registry
# =============================================================================
class ModelRegistry:
    def __init__(self):
        self.models = []

    def register(self, name, version, metrics):
        self.models.append({
            "name": name,
            "version": version,
            "metrics": metrics,
        })

    def get_best(self, metric="accuracy", higher_is_better=True):
        if not self.models:
            return None
        key = lambda m: m["metrics"].get(metric, 0)
        return max(self.models, key=key) if higher_is_better else min(self.models, key=key)

    def list_versions(self, name):
        return [m for m in self.models if m["name"] == name]

    def compare(self, name_a, name_b):
        a = [m for m in self.models if m["name"] == name_a]
        b = [m for m in self.models if m["name"] == name_b]
        best_a = max(a, key=lambda m: m["metrics"].get("accuracy", 0)) if a else None
        best_b = max(b, key=lambda m: m["metrics"].get("accuracy", 0)) if b else None
        return {"a": best_a, "b": best_b}

    def __str__(self):
        return (f"ModelRegistry({len(self.models)} models, "
                f"{len(set(m['name'] for m in self.models))} unique)")


# =============================================================================
# Exercise 6: Data Pipeline Builder
# =============================================================================
class Pipeline:
    def __init__(self):
        self.steps = []

    def add_step(self, name, func):
        self.steps.append((name, func))
        return self

    def run(self, data):
        result = data
        for name, func in self.steps:
            result = func(result)
        return result

    def describe(self):
        names = [name for name, _ in self.steps]
        print(" -> ".join(names))


# =============================================================================
# Test all solutions
# =============================================================================
if __name__ == "__main__":
    print("Chapter 1 Solutions - Verification\n")

    # Ex 1
    print("Exercise 1:")
    for val in [42, -3.14, "hello", [1, 2, 3], True, None]:
        print(f"  {str(val):>15} -> {type_detective(val)}")

    # Ex 2
    print("\nExercise 2:")
    for b in batch_stats(list(range(1, 11)), 3):
        print(f"  Batch {b['batch']}: {b}")

    # Ex 3
    print("\nExercise 3:")
    tokens, vocab = tokenize("The quick brown fox jumps over the lazy dog.")
    print(f"  Tokens: {tokens}")
    print(f"  Vocab: {sorted(vocab)}")

    # Ex 4
    print("\nExercise 4:")
    result = analyze_training({
        "train_loss": [0.9, 0.5, 0.3, 0.15, 0.08],
        "val_loss": [0.95, 0.55, 0.35, 0.32, 0.40],
    })
    for k, v in result.items():
        print(f"  {k}: {v}")

    # Ex 5
    print("\nExercise 5:")
    reg = ModelRegistry()
    reg.register("bert", "v1", {"accuracy": 0.89})
    reg.register("bert", "v2", {"accuracy": 0.93})
    reg.register("gpt", "v1", {"accuracy": 0.91})
    print(f"  {reg}")
    best = reg.get_best()
    print(f"  Best: {best['name']} {best['version']} ({best['metrics']['accuracy']:.0%})")

    # Ex 6
    print("\nExercise 6:")
    pipe = Pipeline()
    pipe.add_step("lowercase", str.lower)
    pipe.add_step("strip", str.strip)
    pipe.add_step("split", str.split)
    result = pipe.run("  Hello World  ")
    print(f"  Result: {result}")
    print("  Pipeline: ", end="")
    pipe.describe()

    print("\nAll solutions verified!")
