"""
Chapter 7 Exercises: Supervised Learning - Regression & Classification

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np


# =============================================================================
# Exercise 1: Implement Linear Regression with Gradient Descent From Scratch
# =============================================================================
# Build a LinearRegression class that uses gradient descent to minimize MSE.
# Support multiple features: y = X @ w + b
#
# Methods:
#   - fit(X, y): Run gradient descent for epochs iterations
#   - predict(X): Return X @ w + b
#   - score(X, y): Return R² (1 - SS_res / SS_tot)
#
# Hint: MSE gradient = (2/n) * X.T @ (X @ w + b - y) for weights,
#       (2/n) * sum(pred - y) for intercept

class LinearRegressionGD:
    def __init__(self, learning_rate=0.01, epochs=1000):
        # YOUR CODE HERE
        pass

    def fit(self, X, y):
        # YOUR CODE HERE
        pass

    def predict(self, X):
        # YOUR CODE HERE
        pass

    def score(self, X, y):
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 2: Implement Logistic Regression From Scratch
# =============================================================================
# Build a LogisticRegression class for binary classification.
# Use sigmoid(z) = 1 / (1 + exp(-z)) and cross-entropy gradient.
#
# Methods:
#   - fit(X, y): Gradient descent with learning_rate, epochs
#   - predict_proba(X): Return P(y=1|X)
#   - predict(X, threshold=0.5): Return 0 or 1
#
# Hint: Gradient for logistic = (1/n) * X.T @ (sigmoid(X@w+b) - y)

class LogisticRegressionScratch:
    def __init__(self, learning_rate=0.1, epochs=1000):
        # YOUR CODE HERE
        pass

    def fit(self, X, y):
        # YOUR CODE HERE
        pass

    def predict_proba(self, X):
        # YOUR CODE HERE
        pass

    def predict(self, X, threshold=0.5):
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 3: Build a Decision Tree Classifier (Simplified, max_depth=3)
# =============================================================================
# Implement a simple decision tree that:
#   - Splits on the feature that gives best Gini impurity reduction
#   - Stops at max_depth=3 or when node is pure
#   - Leaf nodes predict the majority class
#
# You may use recursion. Store: feature_idx, threshold, left_child, right_child,
# and for leaves: predicted_class.

class SimpleDecisionTree:
    def __init__(self, max_depth=3):
        # YOUR CODE HERE
        pass

    def fit(self, X, y):
        # YOUR CODE HERE
        pass

    def predict(self, X):
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 4: Implement Bagging Ensemble From Scratch
# =============================================================================
# Implement a BaggingClassifier that:
#   - Creates n_estimators bootstrap samples (sample with replacement, same size)
#   - Trains a base_estimator on each bootstrap sample
#   - Predicts by majority vote across all estimators
#
# Example usage:
#   bag = BaggingClassifier(base_estimator=MyClassifier(), n_estimators=10)
#   bag.fit(X, y)
#   bag.predict(X_test)

class BaggingClassifier:
    def __init__(self, base_estimator, n_estimators=10):
        # YOUR CODE HERE
        pass

    def fit(self, X, y):
        # YOUR CODE HERE
        pass

    def predict(self, X):
        # YOUR CODE HERE
        pass


# =============================================================================
# Exercise 5: End-to-End Loan Default Prediction System
# =============================================================================
# Build a complete pipeline that:
#   1. Loads the credit dataset from datasets/credit.csv
#   2. Splits into train/test (80/20)
#   3. Scales features with StandardScaler
#   4. Trains at least 2 classifiers (e.g., LogisticRegression, RandomForest)
#   5. Evaluates with accuracy, precision, recall, F1, and ROC-AUC
#   6. Returns the best model and its metrics
#
# Return a dict: {"best_model": model, "metrics": {...}, "predictions": y_pred}

def build_loan_default_pipeline(csv_path="datasets/credit.csv"):
    # YOUR CODE HERE
    pass
