"""
ML Project Template — Ideal patterns for production-quality ML code.

Demonstrates: Config class, DataLoader, Model, Trainer, Evaluator with clean
separation of concerns, proper logging, and error handling.

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import logging
from dataclasses import dataclass
from typing import List, Tuple, Optional

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)


# -----------------------------------------------------------------------------
# Config
# -----------------------------------------------------------------------------

@dataclass
class Config:
    """Centralized configuration. Replace with YAML/JSON loading in production."""
    learning_rate: float = 0.01
    epochs: int = 1000
    batch_size: int = 32
    model_name: str = "linear"

    def validate(self) -> None:
        """Fail fast on invalid config."""
        if self.learning_rate <= 0:
            raise ValueError("learning_rate must be positive")
        if self.epochs < 1:
            raise ValueError("epochs must be >= 1")
        logger.info("Config validated: lr=%.4f, epochs=%d", self.learning_rate, self.epochs)


# -----------------------------------------------------------------------------
# DataLoader
# -----------------------------------------------------------------------------

class DataLoader:
    """Load and expose features and targets. Single responsibility."""

    def __init__(self, features: List[List[float]], targets: List[float]):
        if len(features) != len(targets):
            raise ValueError("Features and targets must have same length")
        self.features = features
        self.targets = targets
        logger.info("DataLoader: %d samples loaded", len(features))

    def get_xy(self) -> Tuple[List[List[float]], List[float]]:
        """Return (features, targets)."""
        return self.features, self.targets

    @classmethod
    def from_rows(cls, data: List[List[float]], target_idx: int = -1) -> "DataLoader":
        """Create from rows; target_idx specifies target column (default: last)."""
        features = [row[:target_idx] for row in data]
        targets = [row[target_idx] for row in data]
        return cls(features, targets)


# -----------------------------------------------------------------------------
# Model
# -----------------------------------------------------------------------------

class LinearModel:
    """Simple linear model: y = W @ x + b (single output for simplicity)."""

    def __init__(self, in_features: int):
        self.in_features = in_features
        self.w = [0.0] * in_features
        self.b = 0.0

    def predict(self, X: List[List[float]]) -> List[float]:
        """Return predictions for each row."""
        return [sum(wi * xi for wi, xi in zip(self.w, row)) + self.b for row in X]

    def fit_step(self, X: List[List[float]], y: List[float], lr: float) -> None:
        """One gradient descent step for MSE."""
        n = len(X)
        preds = self.predict(X)
        errors = [p - t for p, t in zip(preds, y)]
        for j in range(self.in_features):
            grad_wj = (2 / n) * sum(e * row[j] for e, row in zip(errors, X))
            self.w[j] -= lr * grad_wj
        grad_b = (2 / n) * sum(errors)
        self.b -= lr * grad_b


# -----------------------------------------------------------------------------
# Trainer
# -----------------------------------------------------------------------------

class Trainer:
    """Orchestrate training. Depends on Model and Config (injectable)."""

    def __init__(self, model: LinearModel, config: Config):
        self.model = model
        self.config = config

    def fit(self, data: DataLoader) -> None:
        """Train model on data."""
        X, y = data.get_xy()
        logger.info("Training started for %d epochs", self.config.epochs)
        try:
            for epoch in range(self.config.epochs):
                self.model.fit_step(X, y, self.config.learning_rate)
                if (epoch + 1) % 200 == 0:
                    preds = self.model.predict(X)
                    mse = Evaluator.mse(preds, y)
                    logger.info("Epoch %d: MSE=%.6f", epoch + 1, mse)
            logger.info("Training complete")
        except Exception as e:
            logger.exception("Training failed: %s", e)
            raise


# -----------------------------------------------------------------------------
# Evaluator
# -----------------------------------------------------------------------------

class Evaluator:
    """Compute evaluation metrics. Static methods for stateless evaluation."""

    @staticmethod
    def mse(predictions: List[float], targets: List[float]) -> float:
        """Mean squared error."""
        if len(predictions) != len(targets):
            raise ValueError("Predictions and targets must have same length")
        n = len(predictions)
        return sum((p - t) ** 2 for p, t in zip(predictions, targets)) / n

    @staticmethod
    def mae(predictions: List[float], targets: List[float]) -> float:
        """Mean absolute error."""
        n = len(predictions)
        return sum(abs(p - t) for p, t in zip(predictions, targets)) / n


# -----------------------------------------------------------------------------
# Main Pipeline
# -----------------------------------------------------------------------------

def run_pipeline(config: Optional[Config] = None) -> Tuple[LinearModel, float]:
    """Run full pipeline: config -> data -> model -> train -> evaluate."""
    config = config or Config()
    config.validate()

    # Synthetic data: y ≈ 2*x1 + 3*x2
    data = DataLoader.from_rows([
        [1, 2, 8.1],
        [2, 3, 13.1],
        [3, 1, 9.2],
        [4, 4, 20.2],
    ], target_idx=-1)

    model = LinearModel(in_features=2)
    trainer = Trainer(model, config)
    trainer.fit(data)

    X, y = data.get_xy()
    preds = model.predict(X)
    mse = Evaluator.mse(preds, y)
    logger.info("Final MSE: %.6f", mse)
    return model, mse


if __name__ == "__main__":
    model, mse = run_pipeline()
    print(f"\nTrained model weights: w={model.w}, b={model.b}")
    print(f"Final MSE: {mse:.6f}")
