"""
Helper functions demonstrating clean code principles.

- Normalize: DRY for preprocessing
- Safe division: avoid division by zero
- Type hints and docstrings throughout

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

from typing import List, Tuple, Optional


def normalize(
    values: List[float],
    mean: Optional[float] = None,
    std: Optional[float] = None,
) -> Tuple[List[float], float, float]:
    """
    Z-score normalize: (x - mean) / std.

    Args:
        values: Input values to normalize.
        mean: Optional precomputed mean. If None, computed from values.
        std: Optional precomputed std. If None, computed from values.

    Returns:
        Tuple of (normalized_values, mean_used, std_used).
    """
    n = len(values)
    if n == 0:
        return [], 0.0, 0.0

    mean = mean if mean is not None else sum(values) / n
    variance = sum((x - mean) ** 2 for x in values) / n
    std = std if std is not None else (variance ** 0.5)

    if std == 0:
        return [0.0] * n, mean, 0.0

    normalized = [(x - mean) / std for x in values]
    return normalized, mean, std


def safe_divide(a: float, b: float, default: float = 0.0) -> float:
    """Return a/b, or default if b is zero."""
    return a / b if b != 0 else default


def clip_values(
    values: List[float],
    low: float = -3.0,
    high: float = 3.0,
) -> List[float]:
    """Clip values to [low, high]. Useful after normalization."""
    return [max(low, min(high, x)) for x in values]


def compute_mse(predictions: List[float], targets: List[float]) -> float:
    """Mean squared error. Deterministic and testable."""
    if len(predictions) != len(targets):
        raise ValueError("predictions and targets must have same length")
    n = len(predictions)
    if n == 0:
        return 0.0
    return sum((p - t) ** 2 for p, t in zip(predictions, targets)) / n


def split_train_val(
    features: List[List[float]],
    targets: List[float],
    val_ratio: float = 0.2,
) -> Tuple[
    List[List[float]], List[float],
    List[List[float]], List[float],
]:
    """
    Split into train and validation sets (simple sequential split).

    Returns:
        (X_train, y_train, X_val, y_val)
    """
    if val_ratio < 0 or val_ratio >= 1:
        raise ValueError("val_ratio must be in [0, 1)")
    n = len(features)
    split_idx = int(n * (1 - val_ratio))
    return (
        features[:split_idx], targets[:split_idx],
        features[split_idx:], targets[split_idx:],
    )
