"""
Chapter 4 Exercises: Probability & Statistics

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""


# =============================================================================
# Exercise 1: Compute Conditional Probabilities from a Confusion Matrix
# =============================================================================
# Given a 2x2 confusion matrix: [[TP, FN], [FP, TN]]
# Compute: P(predicted positive | actual positive) and P(actual positive | predicted positive)
#
# Example:
#   cm = [[80, 20], [10, 90]]  # TP=80, FN=20, FP=10, TN=90
#   Should compute sensitivity (recall) and precision

def conditional_from_confusion_matrix(tp, fn, fp, tn):
    """
    Return (sensitivity, precision) where:
    sensitivity = P(pred+ | actual+) = TP/(TP+FN)
    precision = P(actual+ | pred+) = TP/(TP+FP)
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 2: Simulate and Verify the Monty Hall Problem
# =============================================================================
# Monty Hall: 3 doors, 1 car, 2 goats. You pick a door. Monty opens a goat door.
# Should you switch? Simulate 10,000 games for both strategies and return
# (win_rate_switch, win_rate_stay).

import random


def monty_hall_simulation(n_games=10000):
    """
    Simulate n_games. Return (win_rate_when_switch, win_rate_when_stay).
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 3: Implement Naive Bayes Classifier from Scratch
# =============================================================================
# Binary classification. Fit on (X, y) where X is list of dicts (word counts),
# y is list of 0/1. Predict class for a new dict using P(c)*∏ P(word|c).
#
# Assume Laplace smoothing: P(word|c) = (count + 1) / (total + vocab_size)

def naive_bayes_fit(X, y):
    """
    X: list of dicts, each dict is {word: count}
    y: list of 0 or 1 (class labels)
    Return learned params: e.g., {p_class0, p_class1, word_probs_given_class0, word_probs_given_class1}
    """
    # YOUR CODE HERE
    pass


def naive_bayes_predict(params, x):
    """
    params: from naive_bayes_fit
    x: dict {word: count}
    Return predicted class (0 or 1)
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 4: Bootstrap Confidence Interval for Model Accuracy
# =============================================================================
# Given predictions and true labels (both lists of 0/1), compute bootstrap
# 95% CI for accuracy. n_bootstrap=1000.
#
# Accuracy = fraction of correct predictions. Resample (predictions, labels)
# together with replacement, compute accuracy each time, then get 2.5th and
# 97.5th percentiles.

def bootstrap_accuracy_ci(predictions, labels, n_bootstrap=1000):
    """
    Return (lower, upper) for 95% bootstrap CI of accuracy.
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# Exercise 5: Design and Analyze an A/B Test for Two ML Models
# =============================================================================
# You have results: model_a_correct = 85 out of 100, model_b_correct = 78 out of 100.
# Perform two-proportion z-test. Return (z_statistic, p_value, conclusion)
# where conclusion is "reject" or "fail_to_reject" at alpha=0.05.

def ab_test_analysis(n_a, conv_a, n_b, conv_b, alpha=0.05):
    """
    Two-proportion z-test. Return (z, p_value, conclusion).
    conclusion is "reject" or "fail_to_reject".
    """
    # YOUR CODE HERE
    pass


if __name__ == "__main__":
    print("Chapter 4 Exercises")
    print("=" * 40)
    print("Implement the functions above,")
    print("then check solutions/solutions.py!")
