#!/usr/bin/env python3
"""
ML Toolkit - Reusable Machine Learning Functions

Core functions for the Berta AI ML curriculum: data loading, splitting,
feature creation, training, evaluation, and visualization.

Usage:
    python scripts/ml_toolkit.py

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    mean_squared_error, accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix
)
import os


# -----------------------------------------------------------------------------
# Data loading and splitting
# -----------------------------------------------------------------------------

def load_and_split_data(
    filepath,
    target_col,
    feature_cols=None,
    test_size=0.2,
    val_size=0.0,
    random_state=42,
):
    """
    Load a CSV and split into train/val/test sets.
    Returns (X_train, X_val, X_test, y_train, y_val, y_test) or
    (X_train, X_test, y_train, y_test) if val_size=0.
    """
    df = pd.read_csv(filepath)
    if feature_cols is None:
        feature_cols = [c for c in df.columns if c != target_col]
    X = df[feature_cols]
    y = df[target_col]
    for col in X.select_dtypes(include=["object"]).columns:
        X = X.copy()
        X[col] = LabelEncoder().fit_transform(X[col].astype(str))
    X = X.fillna(X.median())
    if val_size > 0:
        X_train, X_temp, y_train, y_temp = train_test_split(
            X, y, test_size=test_size + val_size, random_state=random_state
        )
        rel_val = val_size / (test_size + val_size)
        X_val, X_test, y_val, y_test = train_test_split(
            X_temp, y_temp, test_size=1 - rel_val, random_state=random_state
        )
        return X_train, X_val, X_test, y_train, y_val, y_test
    return train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )


def create_features(X, polynomial_degree=1, scale=False):
    """
    Create polynomial features and optionally scale.
    Returns (X_transformed, scaler or None)
    """
    from sklearn.preprocessing import PolynomialFeatures
    poly = PolynomialFeatures(degree=polynomial_degree, include_bias=False)
    X_poly = poly.fit_transform(X)
    scaler = None
    if scale:
        scaler = StandardScaler()
        X_poly = scaler.fit_transform(X_poly)
    return X_poly, scaler


# -----------------------------------------------------------------------------
# Training and evaluation
# -----------------------------------------------------------------------------

def train_model(X_train, y_train, model_type="linear", **kwargs):
    """Train a model. model_type: 'linear', 'logistic', 'random_forest'."""
    if model_type == "linear":
        model = LinearRegression(**kwargs)
    elif model_type == "logistic":
        model = LogisticRegression(max_iter=1000, **kwargs)
    elif model_type == "random_forest":
        model = RandomForestClassifier(**kwargs)
    else:
        raise ValueError(f"Unknown model_type: {model_type}")
    model.fit(X_train, y_train)
    return model


def evaluate_model(model, X_test, y_test, task="regression"):
    """
    Evaluate model. task: 'regression' or 'classification'.
    Returns dict of metrics.
    """
    y_pred = model.predict(X_test)
    if task == "regression":
        return {
            "mse": mean_squared_error(y_test, y_pred),
            "rmse": np.sqrt(mean_squared_error(y_test, y_pred)),
        }
    else:
        return {
            "accuracy": accuracy_score(y_test, y_pred),
            "precision": precision_score(y_test, y_pred, zero_division=0),
            "recall": recall_score(y_test, y_pred, zero_division=0),
            "f1": f1_score(y_test, y_pred, zero_division=0),
        }


def cross_validate(X, y, model, cv=5, scoring="neg_mean_squared_error"):
    """Run k-fold cross-validation. Returns mean and std of scores."""
    kf = KFold(n_splits=cv, shuffle=True, random_state=42)
    scores = cross_val_score(model, X, y, cv=kf, scoring=scoring)
    if "neg_" in scoring:
        scores = -scores
    return scores.mean(), scores.std()


# -----------------------------------------------------------------------------
# Visualization
# -----------------------------------------------------------------------------

def plot_confusion_matrix(y_true, y_pred, title="Confusion Matrix", ax=None):
    """Plot confusion matrix heatmap."""
    cm = confusion_matrix(y_true, y_pred)
    if ax is None:
        fig, ax = plt.subplots(figsize=(6, 4))
    im = ax.imshow(cm, cmap="Blues")
    n_classes = cm.shape[0]
    ax.set_xticks(range(n_classes))
    ax.set_yticks(range(n_classes))
    for i in range(n_classes):
        for j in range(n_classes):
            ax.text(j, i, str(cm[i, j]), ha="center", va="center", fontsize=14)
    plt.colorbar(im, ax=ax)
    ax.set_title(title)
    return ax


def plot_learning_curve(
    model, X, y, train_sizes=None, cv=5, scoring="neg_mean_squared_error"
):
    """
    Plot learning curve: train and val score vs training set size.
    """
    from sklearn.model_selection import learning_curve
    if train_sizes is None:
        train_sizes = np.linspace(0.2, 1.0, 8)
    train_sz, train_scores, val_scores = learning_curve(
        model, X, y, train_sizes=train_sizes, cv=cv, scoring=scoring
    )
    if "neg_" in scoring:
        train_scores, val_scores = -train_scores, -val_scores
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(train_sz, train_scores.mean(axis=1), "b-o", label="Train")
    ax.fill_between(
        train_sz,
        train_scores.mean(axis=1) - train_scores.std(axis=1),
        train_scores.mean(axis=1) + train_scores.std(axis=1),
        alpha=0.2,
        color="blue",
    )
    ax.plot(train_sz, val_scores.mean(axis=1), "r-s", label="Validation")
    ax.fill_between(
        train_sz,
        val_scores.mean(axis=1) - val_scores.std(axis=1),
        val_scores.mean(axis=1) + val_scores.std(axis=1),
        alpha=0.2,
        color="red",
    )
    ax.set_xlabel("Training set size")
    ax.set_ylabel("Score (lower is better for MSE)")
    ax.set_title("Learning Curve")
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    return ax


def plot_feature_importance(model, feature_names, ax=None):
    """Plot feature importance (for tree-based models)."""
    imp = model.feature_importances_
    idx = np.argsort(imp)
    if ax is None:
        fig, ax = plt.subplots(figsize=(8, max(4, len(feature_names) * 0.3)))
    ax.barh([feature_names[i] for i in idx], imp[idx], color="steelblue")
    ax.set_xlabel("Importance")
    ax.set_title("Feature Importance")
    plt.tight_layout()
    return ax


def compare_models(X_train, y_train, X_test, y_test, models, task="classification"):
    """
    Train and compare multiple models. models: dict of name -> model instance.
    Returns DataFrame of metrics.
    """
    results = []
    for name, model in models.items():
        model.fit(X_train, y_train)
        metrics = evaluate_model(model, X_test, y_test, task=task)
        metrics["model"] = name
        results.append(metrics)
    return pd.DataFrame(results)


# -----------------------------------------------------------------------------
# __main__ demo
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    print("ML Toolkit - Demo\n" + "=" * 40)

    np.random.seed(42)
    X = np.random.randn(200, 3)
    y = (X[:, 0] + 2 * X[:, 1] - X[:, 2] + np.random.randn(200) * 0.5) > 0

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000),
        "Random Forest": RandomForestClassifier(n_estimators=50),
    }
    df = compare_models(X_train, y_train, X_test, y_test, models)
    print("Model comparison:")
    print(df.to_string(index=False))

    rf = RandomForestClassifier(n_estimators=50).fit(X_train, y_train)
    print("\nFeature importance:")
    for i, imp in enumerate(rf.feature_importances_):
        print(f"  Feature {i}: {imp:.3f}")

    print("\nDemo complete.")
