"""
ML Utilities - Helper Functions for Machine Learning

Reusable helpers for the Berta AI ML curriculum.

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
import pandas as pd


def train_test_split_manual(X, y, test_ratio=0.2, random_state=None):
    """
    Manual train/test split. X and y are arrays or lists.
    Returns (X_train, X_test, y_train, y_test).
    """
    if random_state is not None:
        np.random.seed(random_state)
    n = len(X)
    indices = np.random.permutation(n)
    split = int(n * (1 - test_ratio))
    train_idx, test_idx = indices[:split], indices[split:]
    X_train = np.array(X)[train_idx]
    X_test = np.array(X)[test_idx]
    y_train = np.array(y)[train_idx]
    y_test = np.array(y)[test_idx]
    return X_train, X_test, y_train, y_test


def metrics_from_confusion_matrix(tp, fp, fn, tn):
    """
    Compute accuracy, precision, recall, F1 from confusion matrix counts.
    """
    accuracy = (tp + tn) / (tp + fp + fn + tn) if (tp + fp + fn + tn) > 0 else 0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}


def safe_divide(a, b, default=0.0):
    """Division that returns default if denominator is zero."""
    return a / b if b != 0 else default


def ensure_2d(X):
    """Ensure X is 2D (n_samples, n_features)."""
    X = np.asarray(X)
    if X.ndim == 1:
        return X.reshape(-1, 1)
    return X


def encode_categorical(df, columns):
    """Encode categorical columns with LabelEncoder. Returns transformed DataFrame."""
    from sklearn.preprocessing import LabelEncoder
    df = df.copy()
    for col in columns:
        if col in df.columns:
            df[col] = LabelEncoder().fit_transform(df[col].astype(str))
    return df


if __name__ == "__main__":
    print("ML Utilities - Demo\n")
    X = list(range(20))
    y = [i % 2 for i in range(20)]
    X_train, X_test, y_train, y_test = train_test_split_manual(X, y, test_ratio=0.2, random_state=42)
    print("Train size:", len(X_train), "Test size:", len(X_test))
    m = metrics_from_confusion_matrix(8, 2, 1, 9)
    print("Metrics (TP=8, FP=2, FN=1, TN=9):", m)
