"""
Chapter 7 Solutions: Supervised Learning - Regression & Classification

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import numpy as np
from pathlib import Path


# =============================================================================
# Exercise 1: Linear Regression with Gradient Descent
# =============================================================================

class LinearRegressionGD:
    def __init__(self, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.intercept = None

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y).ravel()
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        n, p = X.shape
        self.weights = np.zeros(p)
        self.intercept = 0.0
        for _ in range(self.epochs):
            pred = X @ self.weights + self.intercept
            errors = pred - y
            grad_w = (2 / n) * X.T @ errors
            grad_b = (2 / n) * np.sum(errors)
            self.weights -= self.learning_rate * grad_w
            self.intercept -= self.learning_rate * grad_b
        return self

    def predict(self, X):
        X = np.asarray(X)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        return X @ self.weights + self.intercept

    def score(self, X, y):
        y_pred = self.predict(X)
        ss_res = np.sum((y - y_pred) ** 2)
        ss_tot = np.sum((y - np.mean(y)) ** 2)
        return 1 - ss_res / ss_tot if ss_tot > 0 else 0.0


# =============================================================================
# Exercise 2: Logistic Regression From Scratch
# =============================================================================

class LogisticRegressionScratch:
    def __init__(self, learning_rate=0.1, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.intercept = None

    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-np.clip(z, -500, 500)))

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y).ravel()
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        n, p = X.shape
        self.weights = np.zeros(p)
        self.intercept = 0.0
        for _ in range(self.epochs):
            logits = X @ self.weights + self.intercept
            probs = self._sigmoid(logits)
            errors = probs - y
            grad_w = (1 / n) * X.T @ errors
            grad_b = (1 / n) * np.sum(errors)
            self.weights -= self.learning_rate * grad_w
            self.intercept -= self.learning_rate * grad_b
        return self

    def predict_proba(self, X):
        X = np.asarray(X)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        return self._sigmoid(X @ self.weights + self.intercept)

    def predict(self, X, threshold=0.5):
        return (self.predict_proba(X) >= threshold).astype(int)


# =============================================================================
# Exercise 3: Simple Decision Tree (max_depth=3)
# =============================================================================

def _gini(y):
    if len(y) == 0:
        return 0
    p1 = np.mean(y)
    p0 = 1 - p1
    return 1 - p0**2 - p1**2


def _best_split(X, y):
    best_gain, best_feat, best_thr = -1, -1, None
    gini_parent = _gini(y)
    n = len(y)
    for j in range(X.shape[1]):
        vals = np.unique(X[:, j])
        for v in vals[:-1]:
            left = y[X[:, j] <= v]
            right = y[X[:, j] > v]
            if len(left) == 0 or len(right) == 0:
                continue
            gini_child = (len(left) / n) * _gini(left) + (len(right) / n) * _gini(right)
            gain = gini_parent - gini_child
            if gain > best_gain:
                best_gain, best_feat, best_thr = gain, j, v
    return best_feat, best_thr, best_gain


class SimpleDecisionTree:
    def __init__(self, max_depth=3):
        self.max_depth = max_depth
        self.tree = None

    def _fit_rec(self, X, y, depth):
        if depth >= self.max_depth or len(np.unique(y)) == 1:
            return {"leaf": True, "class": int(np.round(np.mean(y)))}
        feat, thr, gain = _best_split(X, y)
        if gain <= 0:
            return {"leaf": True, "class": int(np.round(np.mean(y)))}
        left_idx = X[:, feat] <= thr
        right_idx = ~left_idx
        return {
            "leaf": False,
            "feat": feat,
            "thr": thr,
            "left": self._fit_rec(X[left_idx], y[left_idx], depth + 1),
            "right": self._fit_rec(X[right_idx], y[right_idx], depth + 1),
        }

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y).ravel()
        self.tree = self._fit_rec(X, y, 0)
        return self

    def _predict_one(self, node, x):
        if node["leaf"]:
            return node["class"]
        if x[node["feat"]] <= node["thr"]:
            return self._predict_one(node["left"], x)
        return self._predict_one(node["right"], x)

    def predict(self, X):
        X = np.asarray(X)
        return np.array([self._predict_one(self.tree, x) for x in X])


# =============================================================================
# Exercise 4: Bagging Ensemble From Scratch
# =============================================================================

class BaggingClassifier:
    def __init__(self, base_estimator, n_estimators=10):
        self.base_estimator = base_estimator
        self.n_estimators = n_estimators
        self.estimators = []

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y)
        n = len(y)
        self.estimators = []
        for _ in range(self.n_estimators):
            idx = np.random.choice(n, size=n, replace=True)
            X_boot, y_boot = X[idx], y[idx]
            try:
                from sklearn.base import clone
                est = clone(self.base_estimator)
            except Exception:
                est = type(self.base_estimator)()
            est.fit(X_boot, y_boot)
            self.estimators.append(est)
        return self

    def predict(self, X):
        X = np.asarray(X)
        votes = np.array([est.predict(X) for est in self.estimators])
        return np.round(np.mean(votes, axis=0)).astype(int)


# Simpler BaggingClassifier that works with sklearn-like estimators
class BaggingClassifierSklearn:
    def __init__(self, base_estimator, n_estimators=10):
        self.base_estimator = base_estimator
        self.n_estimators = n_estimators
        self.estimators = []

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y)
        n = len(y)
        self.estimators = []
        for _ in range(self.n_estimators):
            idx = np.random.choice(n, size=n, replace=True)
            X_boot, y_boot = X[idx], y[idx]
            try:
                from sklearn.base import clone
                est = clone(self.base_estimator)
            except Exception:
                est = type(self.base_estimator)()
            est.fit(X_boot, y_boot)
            self.estimators.append(est)
        return self

    def predict(self, X):
        X = np.asarray(X)
        votes = np.array([est.predict(X) for est in self.estimators])
        return np.round(np.mean(votes, axis=0)).astype(int)


# =============================================================================
# Exercise 5: Loan Default Prediction Pipeline
# =============================================================================

def build_loan_default_pipeline(csv_path="datasets/credit.csv"):
    try:
        import pandas as pd
        from sklearn.model_selection import train_test_split
        from sklearn.preprocessing import StandardScaler
        from sklearn.linear_model import LogisticRegression
        from sklearn.ensemble import RandomForestClassifier
        from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
    except ImportError:
        return {"best_model": None, "metrics": {}, "predictions": None}

    base = Path(__file__).parent.parent.parent
    path = base / csv_path
    if not path.exists():
        return {"best_model": None, "metrics": {}, "predictions": None}

    df = pd.read_csv(path)
    X = df.drop(columns=["default"])
    y = df["default"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    models = [
        ("LogisticRegression", LogisticRegression(max_iter=1000, random_state=42)),
        ("RandomForest", RandomForestClassifier(n_estimators=50, random_state=42)),
    ]

    best_auc = -1
    best_model = None
    best_name = None
    best_pred = None

    for name, model in models:
        model.fit(X_train_s, y_train)
        y_pred = model.predict(X_test_s)
        y_proba = model.predict_proba(X_test_s)[:, 1] if hasattr(model, "predict_proba") else y_pred
        auc_val = roc_auc_score(y_test, y_proba) if len(np.unique(y_test)) > 1 else 0.5
        if auc_val > best_auc:
            best_auc = auc_val
            best_model = model
            best_name = name
            best_pred = y_pred

    metrics = {
        "accuracy": accuracy_score(y_test, best_pred),
        "precision": precision_score(y_test, best_pred, zero_division=0),
        "recall": recall_score(y_test, best_pred, zero_division=0),
        "f1": f1_score(y_test, best_pred, zero_division=0),
        "roc_auc": best_auc,
    }

    return {"best_model": best_model, "best_name": best_name, "metrics": metrics, "predictions": best_pred}


if __name__ == "__main__":
    print("Chapter 7 Solutions - Verification\n")

    np.random.seed(42)

    # Ex 1
    print("Exercise 1: Linear Regression GD")
    X = np.random.randn(100, 2)
    y = X @ np.array([2.0, -1.0]) + 1 + np.random.randn(100) * 0.2
    lr = LinearRegressionGD(learning_rate=0.1, epochs=500)
    lr.fit(X, y)
    r2 = lr.score(X, y)
    assert r2 > 0.9
    print(f"  R² = {r2:.4f} (expect > 0.9)")

    # Ex 2
    print("\nExercise 2: Logistic Regression")
    from sklearn.datasets import make_classification
    Xc, yc = make_classification(n_samples=100, n_features=4, random_state=42)
    logr = LogisticRegressionScratch(epochs=500)
    logr.fit(Xc, yc)
    acc = np.mean(logr.predict(Xc) == yc)
    assert acc > 0.8
    print(f"  Accuracy = {acc:.4f} (expect > 0.8)")

    # Ex 3
    print("\nExercise 3: Simple Decision Tree")
    tree = SimpleDecisionTree(max_depth=3)
    tree.fit(Xc, yc)
    pred = tree.predict(Xc)
    assert len(pred) == len(yc)
    print(f"  Predictions shape: {pred.shape}")

    # Ex 4
    print("\nExercise 4: Bagging (using LogisticRegressionScratch)")
    # Use simple base - our LogisticRegressionScratch
    from sklearn.linear_model import LogisticRegression
    bag = BaggingClassifierSklearn(LogisticRegression(max_iter=200), n_estimators=5)
    bag.fit(Xc, yc)
    pred_bag = bag.predict(Xc)
    print(f"  Bagging predictions shape: {pred_bag.shape}")

    # Ex 5
    print("\nExercise 5: Loan Default Pipeline")
    result = build_loan_default_pipeline()
    if result["best_model"] is not None:
        print(f"  Best model: {result.get('best_name', 'N/A')}")
        print(f"  Metrics: {result['metrics']}")
    else:
        print("  (Dataset may not be found - run from chapter root)")

    print("\nAll verifications passed.")
