"""
Chapter 4 Solutions: Probability & Statistics

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

import random
import math


# Exercise 1: Conditional from Confusion Matrix
def conditional_from_confusion_matrix(tp, fn, fp, tn):
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    return sensitivity, precision


# Exercise 2: Monty Hall Simulation
def monty_hall_simulation(n_games=10000):
    wins_switch = 0
    wins_stay = 0
    for _ in range(n_games):
        doors = [0, 1, 2]
        car = random.randint(0, 2)
        choice = random.randint(0, 2)
        # Monty opens a goat door (not chosen, not car)
        goat_doors = [d for d in doors if d != choice and d != car]
        monty_opens = random.choice(goat_doors)
        # Switch: pick the other unopened door
        switch_choice = [d for d in doors if d != choice and d != monty_opens][0]
        if switch_choice == car:
            wins_switch += 1
        if choice == car:
            wins_stay += 1
    return wins_switch / n_games, wins_stay / n_games


# Exercise 3: Naive Bayes Classifier
def naive_bayes_fit(X, y):
    n = len(X)
    n0 = sum(1 for yi in y if yi == 0)
    n1 = n - n0
    p_class0 = n0 / n
    p_class1 = n1 / n
    vocab0 = {}
    vocab1 = {}
    for xi, yi in zip(X, y):
        d = vocab0 if yi == 0 else vocab1
        for w, c in xi.items():
            d[w] = d.get(w, 0) + c
    total0 = sum(vocab0.values())
    total1 = sum(vocab1.values())
    all_words = set(vocab0) | set(vocab1)
    V = len(all_words)
    prob0 = {w: (vocab0.get(w, 0) + 1) / (total0 + V) for w in all_words}
    prob1 = {w: (vocab1.get(w, 0) + 1) / (total1 + V) for w in all_words}
    return {
        "p_class0": p_class0,
        "p_class1": p_class1,
        "prob0": prob0,
        "prob1": prob1,
        "vocab": all_words,
    }


def naive_bayes_predict(params, x):
    log_p0 = math.log(params["p_class0"])
    log_p1 = math.log(params["p_class1"])
    for w, c in x.items():
        if w in params["vocab"]:
            log_p0 += c * math.log(params["prob0"].get(w, 1e-10))
            log_p1 += c * math.log(params["prob1"].get(w, 1e-10))
    return 0 if log_p0 >= log_p1 else 1


# Exercise 4: Bootstrap Accuracy CI
def bootstrap_accuracy_ci(predictions, labels, n_bootstrap=1000):
    n = len(predictions)
    accs = []
    for _ in range(n_bootstrap):
        idx = [random.randint(0, n - 1) for _ in range(n)]
        correct = sum(1 for i in idx if predictions[i] == labels[i])
        accs.append(correct / n)
    accs.sort()
    low = accs[int(0.025 * n_bootstrap)]
    high = accs[int(0.975 * n_bootstrap)]
    return low, high


# Exercise 5: A/B Test Analysis
def ab_test_analysis(n_a, conv_a, n_b, conv_b, alpha=0.05):
    p_a = conv_a / n_a if n_a > 0 else 0.0
    p_b = conv_b / n_b if n_b > 0 else 0.0
    p_pool = (conv_a + conv_b) / (n_a + n_b) if (n_a + n_b) > 0 else 0.0
    se = math.sqrt(p_pool * (1 - p_pool) * (1 / n_a + 1 / n_b)) if (n_a + n_b) > 0 else 0.0
    if se == 0:
        return 0.0, 1.0, "fail_to_reject"
    z = (p_a - p_b) / se
    p_value = 2 * (1 - _norm_cdf(abs(z)))
    conclusion = "reject" if p_value < alpha else "fail_to_reject"
    return z, p_value, conclusion


def _norm_cdf(x):
    a1, a2, a3, a4, a5 = 0.254829592, -0.284496736, 1.421413741, -1.453152027, 1.061405429
    p = 0.3275911
    t = 1.0 / (1.0 + p * x)
    y = 1.0 - (a1 * t + a2 * t ** 2 + a3 * t ** 3 + a4 * t ** 4 + a5 * t ** 5) * math.exp(-x * x / 2)
    return 0.5 * (1.0 + math.copysign(y, x)) if x >= 0 else 1.0 - _norm_cdf(-x)


if __name__ == "__main__":
    print("Chapter 4 Solutions - Verification\n")

    # Ex 1
    print("Exercise 1: Conditional from Confusion Matrix")
    sens, prec = conditional_from_confusion_matrix(80, 20, 10, 90)
    assert abs(sens - 0.8) < 1e-6
    assert abs(prec - 0.888888) < 1e-3
    print(f"  Sensitivity: {sens:.4f}, Precision: {prec:.4f}")

    # Ex 2
    print("\nExercise 2: Monty Hall")
    switch_rate, stay_rate = monty_hall_simulation(10000)
    print(f"  Win rate (switch): {switch_rate:.4f} (expect ~0.67)")
    print(f"  Win rate (stay):   {stay_rate:.4f} (expect ~0.33)")
    assert switch_rate > 0.6 and stay_rate < 0.4

    # Ex 3
    print("\nExercise 3: Naive Bayes")
    X = [{"a": 2, "b": 1}, {"a": 1, "c": 2}, {"b": 2, "c": 1}, {"a": 2, "c": 1}]
    y = [0, 0, 1, 1]
    params = naive_bayes_fit(X, y)
    pred = naive_bayes_predict(params, {"a": 1, "b": 1})
    print(f"  Predict for {{a:1, b:1}}: {pred}")

    # Ex 4
    print("\nExercise 4: Bootstrap Accuracy CI")
    preds = [1, 0, 1, 1, 0, 1, 0, 1, 1, 0]
    labs = [1, 0, 1, 0, 0, 1, 1, 1, 0, 0]
    low, high = bootstrap_accuracy_ci(preds, labs)
    print(f"  95% CI: [{low:.3f}, {high:.3f}]")

    # Ex 5
    print("\nExercise 5: A/B Test")
    z, p, conc = ab_test_analysis(100, 85, 100, 78)
    print(f"  z={z:.3f}, p={p:.4f}, conclusion={conc}")

    print("\nAll solutions verified!")
